test_communication/CMakeLists.txt
test_communication/msg/StaticArrayPrimitives.msg
test_communication/test/message_fixtures.hpp
test_communication/test/test_publisher.cpp
test_communication/test/test_subscriber.cpp

Connects to ros2/ros2#42
Depends on ros2/rmw_connext#36.
@esteve @tfoote @wjwwood Please review.

add test for messages with static arrays

---

test_communication/test/message_fixtures.hpp
test_communication/test/service_fixtures.hpp
test_communication/test/test_publisher.cpp
test_communication/test/test_replier.cpp
test_communication/test/test_requester.cpp
test_communication/test/test_subscriber.cpp

@ros2/owners FYI
This PR implements the changes defined by ros2/design#33.

update message API

---

test_communication/CMakeLists.txt
test_communication/msg/Builtins.msg
test_communication/package.xml

changes to support renaming of interface packages

---

test_communication/CMakeLists.txt

raise warning level

---

test_rclcpp/CMakeLists.txt
test_rclcpp/msg/UInt32.msg
test_rclcpp/package.xml
test_rclcpp/test/test_subscription.cpp

The test currently fails with all rmw implementations.

add test_rclcpp package testing subscriptions and spinning for now

---

test_communication/test/message_fixtures.hpp

http://ci.ros2.org/job/ros2_batch_ci_windows/85/warnings34Result/

fix more windows warnings

---

test_rclcpp/test/test_subscription.cpp

http://ci.ros2.org/job/ros2_batch_ci_osx/59/ passes all tests again.

relax test to make OS X happy

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/test_timer.cpp

http://ci.ros2.org/job/ros2_batch_ci_linux/133/
http://ci.ros2.org/job/ros2_batch_ci_osx/65/
http://ci.ros2.org/job/ros2_batch_ci_windows/92/

add test for timers

---

test_communication/test/test_publisher.cpp
test_communication/test/test_publisher_subscriber.cpp
test_communication/test/test_subscriber.cpp
test_rclcpp/test/test_subscription.cpp
test_rclcpp/test/test_timeout_subscriber.cpp

Added QoS settings

---

test_communication/CMakeLists.txt
test_communication/msg/UInt32.msg
test_communication/test/test_subscription_valid_data.cpp

Connects to ros2/rmw_connext#70

add test to check for receiving callbacks for invalid data

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/test_intra_process.cpp

adding tests for intra process communications

---

test_communication/CMakeLists.txt
test_rclcpp/CMakeLists.txt
test_rclcpp/test/test_intra_process.cpp

This just fixes the existing test.
The assumption that `spin_node_once` will run the callback you think it will does not hold with intra process.

update intra proc tests with different assumptions

---

test_rclcpp/test/test_intra_process.cpp
test_rclcpp/test/test_timeout_subscriber.cpp

use message_info.from_intra_process in test

---

test_rclcpp/test/test_timer.cpp

fix compiler error on windows

---

test_rclcpp/test/test_intra_process.cpp
test_rclcpp/test/test_subscription.cpp
test_rclcpp/test/test_timer.cpp

http://ci.ros2.org/job/ros2_batch_ci_windows/357/

fix warnings on Windows

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/test_spin.cpp

Connects to ros2/rclcpp#111
^ the card for that issue on Waffle disappeared mysteriously, even though I believe I've linked the card correctly. Argh.

Spin until future complete

---

test_communication/test/test_publisher.cpp
test_communication/test/test_publisher_subscriber.cpp
test_communication/test/test_requester.cpp
test_communication/test/test_subscription_valid_data.cpp
test_rclcpp/test/test_repeated_publisher_subscriber.cpp
test_rclcpp/test/test_spin.cpp
test_rclcpp/test/test_timeout_subscriber.cpp
test_rclcpp/test/test_timer.cpp

http://ci.ros2.org/job/ros2_batch_ci_linux/406/
http://ci.ros2.org/job/ros2_batch_ci_osx/303/
http://ci.ros2.org/job/ros2_batch_ci_windows/452/

Reduce test times

---

test_communication/test/test_replier.cpp

disregard duplicate requests

---

test_rclcpp/test/test_subscription.cpp

Test for shared_ptr<const T> callback type

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/test_publisher.cpp

Connects to ros2/design#56
This also uses the new queue_size based api for creating a publisher.

added a test for publishers which uses the const reference api

---

test_rclcpp/test/local_parameters.cpp
test_rclcpp/test/parameter_fixtures.hpp

tests for new parameter to_string API

---

test_communication/test/message_fixtures.hpp
test_communication/test/service_fixtures.hpp
test_communication/test/test_publisher.cpp
test_communication/test/test_publisher_subscriber.cpp
test_communication/test/test_replier.cpp
test_communication/test/test_requester.cpp
test_communication/test/test_subscriber.cpp
test_communication/test/test_subscription_valid_data.cpp
test_rclcpp/test/local_parameters.cpp
test_rclcpp/test/parameter_fixtures.hpp
test_rclcpp/test/test_intra_process.cpp
test_rclcpp/test/test_multiple_service_calls.cpp
test_rclcpp/test/test_parameters_server.cpp
test_rclcpp/test/test_publisher.cpp
test_rclcpp/test/test_remote_parameters.cpp
test_rclcpp/test/test_repeated_publisher_subscriber.cpp
test_rclcpp/test/test_services_client.cpp
test_rclcpp/test/test_spin.cpp
test_rclcpp/test/test_subscription.cpp
test_rclcpp/test/test_timeout_subscriber.cpp
test_rclcpp/test/test_timer.cpp

http://ci.ros2.org/job/ros2_batch_ci_osx/362/

update code to pass ament_cpplint

---

test_rclcpp/test/test_local_parameters.cpp

Fix cpplint warnings
Connects to https://github.com/ros2/ros2/issues/12

Fix cpplint warnings

---

test_rclcpp/test/test_allocator.cpp

use fully qualified name

---

test_rclcpp/test/test_services_client.cpp

Added test to check that the request is returned

---

test_rclcpp/test/test_multiple_service_calls.cpp
test_rclcpp/test/test_spin.cpp
test_rclcpp/test/test_timer.cpp

Finite timer

---

test_rclcpp/test/test_allocator.cpp
test_rclcpp/test/test_multiple_service_calls.cpp

Change State to Impl

---

test_rclcpp/test/test_allocator.cpp

This PR attempts to reduce code duplication in the allocator test by using a test fixture.
It also adds "verbose" (default=false) and "ignore_middleware_tokens" (default=true) booleans to the test cases. Adding "verbose" or "all_tokens" to the invocation of the executable will toggle these options.

Improvements to Allocator test

---

test_rclcpp/test/test_multithreaded.cpp

Specify a publisher queue size large enough to hold all the messages that will be published (in this case it'll be `iterations`), to avoid the possibility that in the intraprocess case we lose messages, causing the test to fail to intermittently.
I identified the problem by instrumenting (with `printf`) the intra process manager, in the place where @wjwwood had already noted that we might want to log the case where a pending message in the ring buffer gets overwritten:  https://github.com/ros2/rclcpp/blob/master/rclcpp/include/rclcpp/intra_process_manager.hpp#L254.
In the course of testing, I found these flags handy to repeat the test until it failed: `--gtest_repeat=-1 --gtest_throw_on_failure`.

Fix multithreaded test by specifying publisher queue size

---

test_rclcpp/test/test_multithreaded.cpp

Make intraprocess more robust with a bounded sleep that checks for the goal condition after publishing (#92).
After discussing the situation with @wjwwood, we agreed that:
* there needs to be some delay between publishing and requiring that the subscriber callback has been invoked, even in the intraprocess request; and
* in lieu of any better API (e.g., waiting on a future associated with the subscriber callback), the best that we can do is to have a bounded sleep loop (which is better than a straight sleep because in the common case we'll exit early, shortening the time required for the test).
So that's what I did here in two places, plus some fixes for use of atomic variables.

Fix intraprocess test failure

---

test_rclcpp/test/test_intra_process.cpp

Adjust sleeps and timeouts to be more robust, especially for Connext on OSX.
Same pattern as #98.

Fix flaky intraprocess test

---

test_rclcpp/test/test_executor.cpp
test_rclcpp/test/test_local_parameters.cpp
test_rclcpp/test/test_multithreaded.cpp

Add two executors spinning in same process test case

---

test_communication/CMakeLists.txt
test_rclcpp/CMakeLists.txt

Connect to ament/ament_tools#72

build release on Windows

---

test_communication/CMakeLists.txt
test_rclcpp/CMakeLists.txt

support multiple type supports per rmw impl

---

test_communication/CMakeLists.txt
test_rclcpp/CMakeLists.txt

use generator expressions for configuration specific tests

---

test_rclcpp/test/test_executor.cpp

The `multiple_executors` test case was sometimes timing out: http://ci.ros2.org/view/nightly/job/nightly_osx/213/testReport/.
In manual testing, I observed that the counter shared between the two threads was sometimes skipping over the goal value of 20, so that neither executor thread would return (they each require the counter to equal the goal value). This is presumably because sometimes the counter increment happens back-to-back in [callback1](https://github.com/ros2/system_tests/blob/master/test_rclcpp/test/test_executor.cpp#L83) and [callback2](https://github.com/ros2/system_tests/blob/master/test_rclcpp/test/test_executor.cpp#L97) without giving either one the chance to compare the counter to the goal value.
This PR gives each thread its own counter, which avoids that race …

Fix race condition in test_executor

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/test_client_scope_client.cpp
test_rclcpp/test/test_client_scope_server.cpp

Add regression test for client scope issue

---

test_rclcpp/test/test_subscription.cpp

See: https://github.com/ros2/system_tests/pull/109#issuecomment-195020801

resolve cpplint warnings

---

test_communication/CMakeLists.txt
test_rclcpp/CMakeLists.txt

Connect to ament/ament_cmake#68

use CTest BUILD_TESTING

---

test_communication/CMakeLists.txt
test_rclcpp/CMakeLists.txt

Ensure using correct rmw implementation in tests

---

test_rclcpp/test/test_executor.cpp

Before: http://ci.ros2.org/job/ci_linux/1430/
After: http://ci.ros2.org/job/ci_linux/1431/

fix compiler warning

---

test_communication/CMakeLists.txt
test_rclcpp/CMakeLists.txt

Connect to ament/ament_cmake#72

require CMake 3.5

---

test_rclcpp/test/parameter_fixtures.hpp

Connects to https://github.com/ros2/rclcpp/issues/196

Update tests for changes in parameter handling

---

test_communication/test/publisher_py.py
test_communication/test/subscriber_py.py

move msg import to top of function

---

test_communication/CMakeLists.txt
test_communication/msg/BoundedArrayNested.msg
test_communication/msg/BoundedArrayPrimitives.msg
test_communication/test/message_fixtures.hpp
test_communication/test/message_fixtures.py
test_communication/test/test_publisher.cpp
test_communication/test/test_publisher_subscriber.cpp
test_communication/test/test_subscriber.cpp

add tests for bounded vectors

---

test_communication/CMakeLists.txt
test_rclcpp/CMakeLists.txt

Since these packages don't export any libraries using these variables doesn't make any sense.
Please review.

remove noops

---

test_rclcpp/test/test_local_parameters.cpp

This PR is a redo of #149, to have the same branch name as ros2/rclcpp#237.

add tests for param helpers (redo of #149)

---

test_rclcpp/test/test_local_parameters.cpp

Tests for https://github.com/ros2/rclcpp/pull/245
Connects to ros2/rclcpp#245

Add tests for getting single parameter from node

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/test_client_scope_consistency_client.cpp
test_rclcpp/test/test_client_scope_consistency_server.cpp

connects to ros2/system_tests#153

Add regression test for different behaviour between first and second client

---

test_communication/test/message_fixtures.hpp
test_communication/test/message_fixtures.py

Requires eProsima/ROS-RMW-Fast-RTPS-cpp#61 to pass.

tests strings > 256

---

test_communication/test/test_requester.cpp
test_rclcpp/CMakeLists.txt
test_rclcpp/include/test_rclcpp/utils.hpp
test_rclcpp/test/pub_sub_fixtures.hpp
test_rclcpp/test/test_client_scope_client.cpp
test_rclcpp/test/test_client_scope_consistency_client.cpp
test_rclcpp/test/test_client_wait_for_service_shutdown.cpp
test_rclcpp/test/test_executor.cpp
test_rclcpp/test/test_multiple_service_calls.cpp
test_rclcpp/test/test_multithreaded.cpp
test_rclcpp/test/test_publisher.cpp
test_rclcpp/test/test_services_client.cpp
test_rclcpp/test/test_subscription.cpp

Connects to ros2/rmw_connext#168.

Local graph changes

---

test_communication/CMakeLists.txt
test_rclcpp/CMakeLists.txt

remove obsolete add_dependencies

---

test_communication/CMakeLists.txt
test_communication/package.xml
test_communication/test/test_messages_c.cpp

using the test_communication message definitions.
Not really ready for review yet.

add a bunch of tests for rcl and rosidl_generator_c messages

---

test_communication/CMakeLists.txt

The tests from #122 were not being ran on windows.
This PR fixes it: CI with passing tests: http://ci.ros2.org/job/ci_windows/1822/

use generator for target file location

---

test_communication/CMakeLists.txt

follow up of https://github.com/ros2/system_tests/pull/152#discussion_r87267525

remove unnecessary ament_index_build_path

---

test_communication/CMakeLists.txt
test_communication/test/replier_py.py
test_communication/test/requester_py.py
test_communication/test/service_fixtures.hpp
test_communication/test/service_fixtures.py
test_communication/test/test_publisher_subscriber.py.in
test_communication/test/test_requester_replier.py.in

connects to https://github.com/ros2/rosidl/issues/67

Test python services

---

test_communication/CMakeLists.txt
test_communication/test/test_publisher_subscriber.py.in
test_communication/test/test_requester_replier.py.in

Use the new `SKIP_TEST` argument
connects to https://github.com/ros2/ros2/issues/290
depends on https://github.com/ament/ament_cmake/pull/80

Mark blacklisted tests as skipped

---

test_communication/CMakeLists.txt
test_rclcpp/CMakeLists.txt

append build space to library path

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/test_services_in_constructor.cpp

This is the test you wanted I think @Karsten1987?
Connects to ros2/rclcpp#277

add test for creating clients and services in a Node constructor

---

test_rclcpp/test/test_client_scope_consistency_client.cpp
test_rclcpp/test/test_client_scope_consistency_server.cpp

Connects to https://github.com/ros2/rmw/issues/85

Rename QoS policies

---

test_communication/test/test_requester.cpp
test_rclcpp/test/test_client_scope_client.cpp
test_rclcpp/test/test_client_scope_consistency_client.cpp
test_rclcpp/test/test_client_wait_for_service_shutdown.cpp
test_rclcpp/test/test_executor.cpp
test_rclcpp/test/test_multiple_service_calls.cpp
test_rclcpp/test/test_multithreaded.cpp
test_rclcpp/test/test_remote_parameters.cpp
test_rclcpp/test/test_services_client.cpp
test_rclcpp/test/test_spin.cpp
test_rclcpp/test/test_subscription.cpp

Related to ros2/rclcpp#284.
Connects to ros2/rclcpp#282

use new rclcpp::literals namespace + constness issue fix

---

test_communication/CMakeLists.txt
test_communication/test/test_messages_c.cpp

Connect to ros2/rosidl_typesupport#6

use rosidl_typesupport_c

---

test_communication/CMakeLists.txt
test_communication/test/publisher_py.py
test_communication/test/replier_py.py
test_communication/test/requester_py.py
test_communication/test/subscriber_py.py
test_communication/test/test_publisher_subscriber.py.in
test_communication/test/test_requester_replier.py.in
test_rclcpp/CMakeLists.txt

use rmw implementation

---

test_communication/test/publisher_py.py
test_communication/test/replier_py.py
test_communication/test/requester_py.py
test_communication/test/subscriber_py.py

Connects to ament/ament_lint#53

Comply with flake8 + flake8-import-order linters

---

test_communication/CMakeLists.txt
test_communication/test/test_messages_c.cpp
test_communication/test/test_publisher_subscriber.cpp
test_communication/test/test_subscriber.cpp
test_rclcpp/CMakeLists.txt

Connects to https://github.com/ros2/ros2/issues/305

Use -Wpedantic

---

test_rclcpp/test/test_local_parameters.cpp

tests for get_parameter_or and set_parameter_if_not_set

---

test_rclcpp/test/test_local_parameters.cpp

See: https://github.com/ros2/system_tests/pull/193#issuecomment-290589395

use 64-bit integer for parameter tests

---

test_communication/test/publisher_py.py
test_communication/test/replier_py.py
test_communication/test/requester_py.py
test_communication/test/subscriber_py.py

use explicit kwargs

---

test_communication/test/test_messages_c.cpp
test_rclcpp/test/test_intra_process.cpp
test_rclcpp/test/test_multithreaded.cpp

support addition of node namespace in rclcpp API

---

test_rclcpp/test/test_multithreaded.cpp

Address issues lingering from #200 .

fix type and style

---

test_communication/CMakeLists.txt

set_tests_properties for correct requester replier executable

---

test_communication/test/test_messages_c.cpp
test_rclcpp/CMakeLists.txt

remove unnecessary topic name check

---

test_communication/test/test_messages_c.cpp

Connect to ros2/rcutils#25.
Please review.

remove unnecessary usage of RCL_S_TO_NS

---

test_communication/test/publisher_py.py

I noticed that the Python test code would crash if it sent all the data but never got sigint'ed.
Connects to ros2/build_cop#29

destroy node before shutdown

---

test_communication/test/test_invalid_secure_node_creation_c.cpp

Use _WIN32 everywhere

---

test_rclcpp/test/parameter_fixtures.hpp

apply forward slash for list_parameters

---

test_rclcpp/CMakeLists.txt

Aiming to fix ros2/build_cop#50.

increase timeout of test

---

test_communication/test/test_invalid_secure_node_creation_c.cpp
test_communication/test/test_messages_c.cpp
test_rclcpp/test/test_client_wait_for_service_shutdown.cpp
test_rclcpp/test/test_executor.cpp
test_rclcpp/test/test_multithreaded.cpp
test_rclcpp/test/test_services_client.cpp
test_rclcpp/test/test_services_in_constructor.cpp
test_rclcpp/test/test_spin.cpp

Connect to ament/uncrustify#18.

update style to match latest uncrustify

---

test_rclcpp/test/test_subscription.cpp

Connect to ament/uncrustify#18.

remove obsolete INDENT-OFF usage

---

test_rclcpp/test/test_remote_parameters.cpp

add test for sync parameter_client

---

test_rclcpp/CMakeLists.txt

fixes https://github.com/ros2/system_tests/pull/231#issuecomment-333902988
related ci:
linux debug: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3299)](http://ci.ros2.org/job/ci_linux/3299/)
osx release: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2632)](http://ci.ros2.org/job/ci_osx/2632/)

increase remote parameter test to 60

---

test_communication/CMakeLists.txt
test_communication/package.xml
test_rclcpp/CMakeLists.txt
test_rclcpp/package.xml
test_security/CMakeLists.txt
test_security/package.xml

Connect to ament/ament_cmake#115.

use ament_cmake_pytest instead of ament_cmake_nose

---

test_communication/test/requester_py.py

Wait for the service to be available before calling it.

Wait for service before calling it

---

test_communication/CMakeLists.txt
test_rclcpp/CMakeLists.txt
test_security/CMakeLists.txt

check if test exists before adding properties

---

test_rclcpp/test/test_multithreaded.cpp

Add cli args to Node constructor

---

test_communication/test/test_publisher_subscriber.py.in
test_communication/test/test_requester_replier.py.in
test_rclcpp/test/test_executable_output.py.in
test_rclcpp/test/test_two_executables.py.in
test_security/test/test_secure_publisher_subscriber.py.in

migrate launch -> launch.legacy

---

test_communication/CMakeLists.txt
test_communication/test/test_message_serialization.cpp

use size_t

---

test_rclcpp/test/test_executor.cpp
test_rclcpp/test/test_local_parameters.cpp

Connects to ament/uncrustify#24

fix indentation to comply with uncrusity 0.67

---

README.md

Takes my comment from #291 and turns it into a very basic README.
connects to #291 
fixes #291

Add a minimal readme linking to an example test.

---

test_rclcpp/test/test_executor.cpp

Add a test for ros2/rclcpp#558
connects to ros2/ros1_bridge#133
Blocks ros2/rviz#354
CI https://github.com/ros2/rviz/pull/354#issuecomment-421519940

Add test for spin_some(max_duration)

---

test_communication/test/test_messages_c.cpp
test_security/test/test_invalid_secure_node_creation_c.cpp

use new error handling API from rcutils

---

test_communication/test/test_message_serialization.cpp
test_communication/test/test_messages_c.cpp

rename dynamic array to sequence

---

test_communication/test/test_messages_c.cpp

Connects to ros2/rcl#335
Now the function takes an optional output index argument.

Update rcl_wait_set_add_guard_condition() call

---

test_communication/test/test_publisher.cpp
test_communication/test/test_publisher_subscriber.cpp
test_communication/test/test_subscriber.cpp

connects to ros2/rcl_interfaces#52

add new fixtures

---

test_communication/CMakeLists.txt
test_communication/package.xml
test_communication/test/test_messages_c.cpp
test_communication/test/test_publisher_subscriber.cpp
test_rclcpp/CMakeLists.txt
test_rclcpp/test/test_avoid_ros_namespace_conventions_qos.cpp
test_rclcpp/test/test_client_scope_client.cpp
test_rclcpp/test/test_client_scope_consistency_client.cpp
test_rclcpp/test/test_client_wait_for_service_shutdown.cpp
test_rclcpp/test/test_executor.cpp
test_rclcpp/test/test_local_parameters.cpp
test_rclcpp/test/test_multiple_service_calls.cpp
test_rclcpp/test/test_multithreaded.cpp
test_rclcpp/test/test_publisher.cpp
test_rclcpp/test/test_remote_parameters.cpp
test_rclcpp/test/test_services_client.cpp
test_rclcpp/test/test_services_in_constructor.cpp
test_rclcpp/test/test_signal_handler_before_shutdown__expected_output.txt
test_rclcpp/test/test_spin.cpp
test_rclcpp/test/test_subscription.cpp
test_rclcpp/test/test_timer.cpp
test_rclcpp/test/test_waitable.cpp
test_security/test/test_invalid_secure_node_creation_c.cpp

refactor to support init options and context

---

test_communication/test/test_messages_c.cpp

pass context to wait set

---

test_rclcpp/test/test_intra_process.cpp
test_rclcpp/test/test_multithreaded.cpp

Connects to [ros2/rclcpp#492](https://github.com/ros2/rclcpp/issues/492)

Update for NodeOptions Node constructor

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/node_check_names.cpp
test_rclcpp/test/test_n_nodes.py.in
test_rclcpp/test/test_ten_nodes.py.in

connects to ros2/rosidl_typesupport_opensplice#17

Add in a test to ensure that 10 nodes can launch simultaneously.

---

test_cli_remapping/package.xml
test_communication/package.xml
test_rclcpp/package.xml
test_security/package.xml

Add launch along with launch_testing as test dependencies.

---

test_communication/test/test_action_client.cpp
test_communication/test/test_action_server.cpp

Cherry pick of 705c7b3
connects to ros2/rosidl_typesupport#45

[Crystal patch 3 backport] Add test for test_msgs/NestedMessage.action (#330)

---

test_communication/CMakeLists.txt
test_communication/test/action_client_py.py
test_communication/test/action_server_py.py

Add communication tests for Python Actions (#333)

---

test_communication/CMakeLists.txt

Partially targets ros2/ros2#658

Using ament_target_dependencies where possible

---

test_rclcpp/test/test_multithreaded.cpp

connects to ros2/rclcpp#673
Signed-off-by: Emerson Knapp <eknapp@amazon.com>

Change use of deprecated rclcpp APIs

---

test_communication/test/test_messages_c.cpp

API updates for RMW preallocation work.

---

test_communication/test/test_publisher.cpp
test_communication/test/test_publisher_subscriber.cpp
test_communication/test/test_subscriber.cpp

add WString tests

---

test_communication/test/test_messages_c.cpp

Fix call to rcl_wait_set_init() after API changed

---

test_cli/test/initial_params.py
test_cli/test/test_params_yaml.py

Parameter API adaptation for https://github.com/ros2/rclpy/pull/325.

Using new parameter API: allowing undeclared parameters.

---

test_cli/test/initial_params.py
test_cli/test/test_params_yaml.py

Connected to https://github.com/ros2/rclpy/pull/339.

Declaring initial parameters.

---

test_cli_remapping/test/name_maker.cpp
test_communication/test/test_publisher.cpp
test_communication/test/test_publisher_subscriber.cpp
test_communication/test/test_publisher_subscriber_serialized.cpp
test_communication/test/test_subscriber.cpp
test_communication/test/test_subscription_valid_data.cpp
test_rclcpp/test/pub_sub_fixtures.hpp
test_rclcpp/test/test_avoid_ros_namespace_conventions_qos.cpp
test_rclcpp/test/test_executor.cpp
test_rclcpp/test/test_intra_process.cpp
test_rclcpp/test/test_multithreaded.cpp
test_rclcpp/test/test_publisher.cpp
test_rclcpp/test/test_repeated_publisher_subscriber.cpp
test_rclcpp/test/test_spin.cpp
test_rclcpp/test/test_subscription.cpp
test_rclcpp/test/test_timeout_subscriber.cpp
test_security/test/test_secure_publisher.cpp
test_security/test/test_secure_subscriber.cpp

changes to avoid deprecated API's

---

test_communication/test/test_subscriber.cpp

Make test_subscriber_cpp always fail gracefully.

---

test_cli_remapping/test/name_maker.py
test_communication/test/publisher_py.py
test_communication/test/subscriber_py.py

Connected to https://github.com/ros2/rclpy/issues/342

Fix deprecation warnings

---

test_cli/test/initial_params.cpp
test_cli/test/initial_params.py
test_cli/test/test_params_yaml.py

Connects to ros2/ros2_documentation#242

update to use new parameter option names

---

test_communication/test/test_replier.cpp
test_communication/test/test_requester.cpp

Connects to https://github.com/ros2/rosidl/pull/387

Support Arrays.srv in communication tests

---

test_cli/test/test_params_yaml.py
test_cli_remapping/test/test_cli_remapping.py

Precisely what the title says. Connected to https://github.com/ros2/rcl/pull/477.

Adapt to '--ros-args ... [--]'-based ROS args extraction

---

test_communication/test/test_messages_c.cpp

rename rosidl_generator_c namespace to rosidl_runtime_c

---

test_security/CMakeLists.txt
test_security/test/test_invalid_secure_node_creation_c.cpp
test_security/test/test_secure_publisher_subscriber.py.in

Related: https://github.com/ros2/sros2/issues/199

Update security environment variables

---

test_communication/test/test_publisher_subscriber_serialized.cpp

connects to https://github.com/ros2/rclcpp/pull/1090

use serialized message in callback

---

pytest.ini

This is part of ros2/ros2#951, which has more explanation and CI.

Add pytest.ini so tests succeed when running locally.

---

test_communication/test/test_publisher_subscriber_serialized.cpp

Though unlikely, I think it's possible for the first couple messages to be missed since we directly
start publishing after creating the subscription. If this happens, it will throw off the expected
value based on the counter. I think this is what was responsible for the reported test failure in #451.
This change accounts for possible missed messages by setting the counter to the value in the first received message.
Resolves #451

Make TestMessageSerialization robust to missed messages

---

test_rclcpp/test/test_services_client.cpp
test_rclcpp/test/test_services_server.cpp

See https://github.com/ros2/rclcpp/pull/1709

Add test for defered service callback signature

---

test_rclcpp/test/test_multiple_service_calls.cpp
test_rclcpp/test/test_multithreaded.cpp

Changes required by https://github.com/ros2/rclcpp/pull/1734.

Fix deprecation warnings and failures after client API update

---

test_cli_remapping/test/name_maker.py
test_communication/test/action_client_py.py
test_communication/test/action_server_py.py

Related to https://github.com/ros2/rclpy/pull/844.

Update python nodes SIGINT handling

---

test_quality_of_service/test/test_best_available.cpp
test_rclcpp/test/test_client_scope_consistency_server.cpp
test_rclcpp/test/test_multithreaded.cpp

Requires ros2/rclcpp#1969
Follow up to #506

Pass rclcpp::QoS to create_service

---

test_rclcpp/test/parameter_fixtures.hpp

This refactor depends on https://github.com/ros2/rclcpp/pull/2300

refactor corrected depth check for prefix in parameter_fixtures.hpp

---

test_quality_of_service/include/test_quality_of_service/qos_utilities.hpp
test_quality_of_service/test/qos_test_publisher.cpp
test_quality_of_service/test/qos_test_subscriber.cpp
test_quality_of_service/test/qos_utilities.cpp

Noticed while doing other debugging.

Cleanup header includes in test_quality_of_service.

---

test_communication/test/subscriber_py.py

Small fix for modern flake8.

---

test_rclcpp/test/test_local_parameters.cpp

This is what you expect @tfoote in this TODO?

Addressed TODO in test_local_parameters

---

test_cli/test/initial_params.py
test_cli/test/test_params_yaml.py
test_cli_remapping/test/name_maker.py
test_communication/test/action_server_py.py
test_communication/test/replier_py.py
test_communication/test/requester_py.py
test_communication/test/subscriber_py.py

This allows us to cleanup, while using a lot less code to try and track it.
This is part of https://github.com/ros2/rclpy/issues/1280

Use rclpy.init context manager where we can.

---

test_rclcpp/test/test_waitable.cpp

This is the counterpart to https://github.com/ros2/rclcpp/pull/2593

Implement the pure-virtual functions in the Waitable class.
