ros2/system_tests

test_communication/CMakeLists.txt
test_communication/msg/Builtins.msg
test_communication/msg/Nested.msg
test_communication/test/message_fixtures.hpp
test_communication/test/test_publisher.cpp
test_communication/test/test_subscriber.cpp

Connects to ros2/ros2#42
@esteve @tfoote @wjwwood Please review.

add tests for nested messages

---

test_communication/test/message_fixtures.hpp

I had to do this to fix a build error on Windows like this:
```
31>c:\dev\ros2\src\ros2\system_tests\test_communication\test\message_fixtures.hpp(113): error C2397: conversion from 'unsigned long' to 'int32_t' requires a narrowing conversion [C:\dev\ros2\build\test_communication\test_subscriber_cpp__rmw_connext_cpp.vcxproj]
...
31>c:\dev\ros2\src\ros2\system_tests\test_communication\test\message_fixtures.hpp(176): error C2398: Element '3': conversion from 'unsigned long' to 'int' requires a narrowing conversion [C:\dev\ros2\build\test_communication\test_subscriber_cpp__rmw_connext_cpp.vcxproj]
```
I followed the suggestion of this SO: http://stackoverflow.com/a/4690988
I'm open to other suggestions, but with this patch I'm able to build our entire stack on Windows (from the cmd prompt the …

fix narrowing conversion error on windows

---

test_communication/test/message_fixtures.hpp

I was getting warnings about too many braces and too few. We'll see if this pull request introduces new warnings or otherwise breaks the Linux or Windows builds.
Connects to ros2/ros2#53

adjust use of braces to fix warnings with clang

---

test_communication/CMakeLists.txt
test_communication/test/test_publisher.cpp
test_communication/test/test_publisher_subscriber.cpp

This test currently fails with the Connext rwm implementations.

add tests for publish/subscribe in a single process

---

test_communication/CMakeLists.txt
test_communication/msg/DynamicArrayNested.msg
test_communication/msg/Nested.msg
test_communication/msg/StaticArrayNested.msg
test_communication/test/message_fixtures.hpp
test_communication/test/test_publisher.cpp
test_communication/test/test_publisher_subscriber.cpp
test_communication/test/test_publisher_subscriber.py.in
test_communication/test/test_requester_replier.py.in
test_communication/test/test_subscriber.cpp

This tests covers the case which currently fails in #14.
I will wait with the merge until a fix has been committed to `rmw_connext_dynamic_cpp`.

add test to cover messages with an array of sub messages

---

test_rclcpp/test/test_subscription.cpp
test_rclcpp/test/test_timer.cpp

The updated test checks that when the subscriber goes out of scope deregisters correctly.
The patch also replaces `std::cout` with `printf` - sorry for mixing it.
Currently the test fails since the subscriber does not deregister itself correctly. It seems like the subscription handle is not yet destroyed because something else hold a shared pointer of it.

update subscription test to check correct deregistration

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/test_subscription.cpp
test_rclcpp/test/test_timeout_subscriber.cpp

Connects to ros2/ros2#73
This test could be prone to flakiness due to scheduling nondeterminism, hence the extremely high tolerance. If we'd prefer to avoid flaky tests, I'm fine with declining this change, but I posted it to prove the correctness of my timeout PRs.

Add test for timeout parameter

---

test_communication/msg/StaticArrayNested.msg
test_communication/test/message_fixtures.hpp

* a string with more then 255 characters
* more than 100 elements in a sequence
Both tests currently fail with Connext 5.1.
Using Connext 5.2 with unbounded support they pass: ros2/rmw_connext#54
A modified test with the limits reduced to 255 and 100 passed: http://ci.ros2.org/job/ros2_batch_ci_linux/55/
This can only be merged once everyone (including the build farm) has updated to Connext 5.2.
Connects to ros2/ros2#70

add fixtures with longer dynamic content

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/test_repeated_publisher_subscriber.cpp

The test fails for `rmw_connext_dynamic_cpp`:
http://ci.ros2.org/job/ros2_batch_ci_linux/228/
http://ci.ros2.org/job/ros2_batch_ci_osx/149/
http://ci.ros2.org/job/ros2_batch_ci_windows/231/

add test with repeated publishers / subscribers

---

test_communication/test/test_replier.cpp

The requester will never send a request which has been answered a second time.
http://ci.ros2.org/job/ros2_batch_ci_linux/267/
http://ci.ros2.org/job/ros2_batch_ci_osx/187/
http://ci.ros2.org/job/ros2_batch_ci_windows/268/

update test to catch repeated service callbacks

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/local_parameters.cpp
test_rclcpp/test/parameter_fixtures.hpp
test_rclcpp/test/test_parameters_server.cpp
test_rclcpp/test/test_parameters_server.py.in
test_rclcpp/test/test_remote_parameters.cpp

This has some basic tests. However I need some help on the RTI Connext Dynamic implmeentation tests which hang. 
How much details do we want to implement before we add support for a testing framework like gtest. Writing detailed unit tests with return values only is not very productive. 
This is currently running the tests and checking their values only. 
Connects to #10

Add tests for parameters

---

test_rclcpp/CMakeLists.txt

Spun off #44, adds GTest include dir. This change however doesn't take effect because the related test is not enabled.

Added GTest include dir

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/test_timer.cpp

This PR moves calls to `rclcpp::init` into a main function to ensure that it's only being called once.

Call rclcpp::init only once

---

test_rclcpp/test/test_subscription.cpp

Connects to ros2/rclcpp#123
Fixes ros2/rclcpp#118
Without the rclcpp pull request, this test fails to compile.

Test publishing a ConstSharedPtr

---

test_rclcpp/test/test_subscription.cpp

add a test which uses the create_subscription with queue size api

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/test_multiple_service_calls.cpp

This new test implement exactly the same test for services as ros2/system_tests#20 does for pub/sub. It covers what has been tracked in ros2/rclcpp#52 for a while.
Without any patches the test fails since most rmw implementations currently don't wake up a second time: http://ci.ros2.org/job/ros2_batch_ci_osx/349/
With the two patches (ros2/rmw_connext#66 ros2/rmw_opensplice#60) the test passes since the rmw implementations check the read correctly (as suggested in https://github.com/ros2/rclcpp/issues/52#issuecomment-126523047): http://ci.ros2.org/job/ros2_batch_ci_osx/350/
Connect to ros2/rclcpp#52

add test with multiple service calls

---

test_communication/test/test_publisher_subscriber.cpp
test_communication/test/test_subscriber.cpp
test_communication/test/test_subscription_valid_data.cpp
test_rclcpp/test/test_intra_process.cpp
test_rclcpp/test/test_publisher.cpp
test_rclcpp/test/test_repeated_publisher_subscriber.cpp
test_rclcpp/test/test_subscription.cpp
test_rclcpp/test/test_timeout_subscriber.cpp

Moved `rmw_qos_profile` argument around to make it optional.
Connects to ros2/ros2#80

Made rmw_qos_profile argument optional

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/parameter_fixtures.hpp
test_rclcpp/test/test_local_parameters.cpp

Make sure that parameters tests are built and run.

Enable parameters tests

---

test_rclcpp/test/test_intra_process.cpp
test_rclcpp/test/test_publisher.cpp
test_rclcpp/test/test_subscription.cpp
test_rclcpp/test/test_timer.cpp

Use `uint32_t` instead of `unsigned long` to comply with `cpplint`
Connects to ament/ament_lint#34

Replace unsigned long with uint32_t

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/test_allocator.cpp

Connects to ros2/rclcpp#137
This test instruments global operator new/delete with counters and provides a custom allocator that calls malloc/free, but counts different global variables. It checks that the allocations/deallocations during runtime are not made within the global new/delete operators, but from the custom allocator. There is a special exception made for calls that originate from within the rmw implementation or DDS implementation, which is accomplished by backtracing the symbols of the stack trace (thus the test must be built in Debug mode).

Allocator template

---

test_rclcpp/test/test_allocator.cpp

Use enable_if to disable the `construct` method if the pointer type is const in the custom allocator.

Fix osx build

---

test_rclcpp/test/test_spin.cpp

`test_spin` contains callbacks specialized for the old behavior of timers. This PR fixes regressions after ros2/rclcpp#146.

fix timer behavior in test_spin

---

test_rclcpp/test/test_spin.cpp

Connects to ros2/rclcpp#149
Change namespace for refactoring and change one test case to invoke `Executor::spin_until_future_complete`.

change namespace of FutureReturnCode

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/test_executor.cpp
test_rclcpp/test/test_spin.cpp

Add test for cancel

---

test_rclcpp/test/test_multiple_service_calls.cpp

I made a similar test to this in my upcoming multithreaded test and I wanted to make a single-threaded version of it as a sanity check. This test case passes, but the multi-threaded case does not.
update: I got the multi-threaded version of this test case working in ros2/system_tests#72, but I'll keep this PR in case the multi-threaded executor breaks in the future.
Depends on ros2/rclcpp#153 and ros2/rmw_opensplice#95

Add new case to multiple_service_calls for "n" clients (currently 5)

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/test_multithreaded.cpp

This PR tests MultiThreadedExecutor `spin` and `spin_some` in 4 test cases:
1. Create 1 publisher and 2*N subscribers where N is the hardware concurrency of the machine, in an attempt to saturate the execution with work that must be done.
2. Same as above, but with intraprocess turned on.
3. Create 1 service and 2*N clients.
4. Create 1 publisher, 1 subscriber, and N timers that all attempt to publish a message on the publisher at the same time.
Connects to ros2/ros2#92

Test for multithreaded execution

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/test_multithreaded.cpp

The test fails on Jenkins because it takes at ~20 seconds with Connext, but the timeout is set to 15.
The test also fails on Windows because of spurious wakeups in the scheduler. This PR adds a 1ms period busy wait to ensure that the condition is met.

Fix multithreaded test on Windows and Jenkins

---

test_rclcpp/test/test_allocator.cpp

ignore_middleware_tokens is the boolean in the allocator logic that causes the test to ignore allocations that originate in the DDS implementation.
--all-tokens is the command line argument flag that causes the test NOT to ignore middleware tokens.
This PR corrects the logic of the test to be consistent with this design.

Reverse ignore logic in allocator test

---

test_rclcpp/test/test_subscription.cpp

adding a test and a commented out test for the bind that doesn't compile

---

test_rclcpp/CMakeLists.txt

This change is intended to fix 4 of the 6 failures (the ones not mentioning "pendulum" in the name) listed here:
http://ci.ros2.org/view/nightly/job/nightly_linux/130/testReport/
Rationale: With the new tests added in #88, the Connext flavors of this test executable are now taking longer to run. Here's timing info from my Linux machine, running the executables directly:
~~~
$ time ./build/test_rclcpp/gtest_subscription__rmw_opensplice_cpp
real    0m1.270s
$ time ./build/test_rclcpp/gtest_subscription__rmw_connext_cpp
real    0m20.203s
$ time ./build/test_rclcpp/gtest_subscription__rmw_connext_dynamic_cpp
real    0m20.201s
~~~
Given that the Connext versions are taking about 20s, it's no wonder that they failed with a timeout of 15s. I'm doubling the timeout to 30s to have some margin.
I …

Increase timeout on subscription test

---

test_rclcpp/CMakeLists.txt

Before: http://ci.ros2.org/job/ci_windows/846/testReport/
After: http://ci.ros2.org/job/ci_windows/848/testReport/

fix missing rmw test suffix

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/test_services_client.cpp
test_rclcpp/test/test_services_server.cpp

Fixes #93
I think there was a problem with crosstalk in DDS entities that weren't finished tearing down. I've separated all nodes and service names for the different cases.
The test is turning over reliably on my machine (has been for over 20 minutes). I'll start a repeat-until-fail job with this test on OSX, since that's the platform where it failed in the nightly job.

Try to fix flaky services test by partitioning topic names

---

test_rclcpp/test/test_subscription.cpp

Fix flaky subscription test by adding:
* a 1ms sleep between setup and the start of publishing; and
* a maximum-2s loop of 10ms sleeps to wait for message delivery.
Both features appear to be required to ensure reliable test results with Connext when the system is under load.
These tests fail under CI most often with Connext on OSX (e.g., http://ci.ros2.org/job/ci_osx/679/testReport/%28root%29/projectroot/gtest_subscription__rmw_connext_cpp/). To reproduce locally, I load my 8-core Linux machine with `stress -c 8`. I consider the problem "fixed" when the test passes under those conditions.

Fix flaky subscription test

---

test_rclcpp/test/test_subscription.cpp

Shows that ros2/rclcpp#179 is fixed, with one caveat--an extra sleep is necessary before publishing.

Spin before subscription: single-threaded

---

test_rclcpp/test/test_spin.cpp
test_rclcpp/test/test_subscription.cpp

So I've attempted to make this test less flaky. What I did was use a `std::shared_future` and `std::promise` so that I could have the executor spin until the predicate was fulfilled. The predicate was that the subscription's callback was called. So I replaced the use of `spin_once` with `spin_until_future_complete`.

changed how the subscription_and_spinning test works

---

test_rclcpp/test/test_intra_process.cpp
test_rclcpp/test/test_multithreaded.cpp
test_rclcpp/test/test_publisher.cpp
test_rclcpp/test/test_subscription.cpp
test_rclcpp/test/test_timer.cpp

There were a lot of warnings when building the `test_rclcpp` package with `RelWithDebInfo` on OS X. Most are comparison between signed/unsigned numbers via (within) gtest macros.

fix comparison warnings within uses of gtest macros

---

test_rclcpp/test/test_publisher.cpp
test_rclcpp/test/test_subscription.cpp

Looks like I got the order wrong on an `ASSERT_GE` when addressing the cpplint warnings. See: https://github.com/ros2/system_tests/pull/109#issuecomment-195020801

fix the order of the assert_ge check in test_publisher

---

test_rclcpp/CMakeLists.txt
test_rclcpp/include/test_rclcpp/utils.hpp
test_rclcpp/test/test_executor.cpp
test_rclcpp/test/test_subscription.cpp

Add tests for notify guard condition in node

---

test_communication/CMakeLists.txt
test_rclcpp/CMakeLists.txt
test_rclcpp/test/test_publisher.cpp

Connects to ros2/rmw#63
Get only the C++ typesupport for each rmw implementation while generating interfaces for the tests.

Get only C++ typesupport implementations

---

test_communication/CMakeLists.txt
test_communication/msg/FieldsWithSameType.msg

Add a message which has multiple fields with the same non-primitive type.
* http://ci.ros2.org/job/ci_linux/1263/
* http://ci.ros2.org/job/ci_osx/1009/
* http://ci.ros2.org/job/ci_windows/1296/
This is mainly to demonstrate that ros2/rmw_opensplice#109 is not necessary. Should we still merge this (to catch potential problems in the future) or just close it?

add message which has fields with the same non-primitive type

---

test_communication/msg/DynamicArrayPrimitives.msg
test_communication/test/message_fixtures.hpp

Unit test for ros2/rclcpp#219.
Currently fails when the publisher and subscriber executables are being invoked separately. The jobs doesn't fail (http://ci.ros2.org/job/ci_linux/1268/) since the multi executable tests are not run: see #119

extend test to cover another case

---

test_communication/test/message_fixtures.hpp

This avoids language specific approximations/rounding on float variables

use values that fit in a float for testing

---

test_communication/test/message_fixtures.hpp

It seems that https://github.com/ros2/system_tests/commit/4f05870ee0fa897cc9a950be59d3219fc3956ebc while fixing some warnings changed the test behavior.
I assume that the "expected" message would be a message with only empty arrays (std::vectors). But adding a second pair of curly brackets results in initializing all vectors with one element set to its default value (e.g. `msg->bool_values={{}}` will result in `{false}`)
It seems that `{{` is needed only when you want to initialize a vector with more than one element.
This would PR allows to get back to what I think was the expected behavior.
Pending CI jobs to confirm that no new warnings show up:
* Linux [![Build Status](http://ci.ros2.org/job/ci_linux/1377/badge/icon)](http://ci.ros2.org/job/ci_linux/1377)
* OSX [![Build …

fix use of bracket

---

test_communication/CMakeLists.txt

Fix wrong CMake variable to reenabled tests with multiple executables. Numerous of the tests are currently failing:
* http://ci.ros2.org/job/ci_linux/1269/
* http://ci.ros2.org/job/ci_osx/1015/
* http://ci.ros2.org/job/ci_windows/1303/

fix generation of tests with multiple executables

---

test_rclcpp/test/test_executor.cpp

It's always a bit unsettling when "just waiting a bit longer" seems to "fix" something, but this seems to eliminate a flaky test failure on Windows that I can reproduce locally only when running the test in the Command Prompt (cmd.exe).
I thought that Jenkins would be running the test binaries through some sort of better i/o capture mechanism, and when I run the binaries using ConEmu (which I thought would be more similar to what Jenkins does) I can't reproduce the failures until I take the timeout down to 3 milliseconds. But anyway making this timeout a bit longer (50 milliseconds) seems to "fix" the test on Command Prompt (I've run it many hundred times now), so I think this is an improvement. :chicken:

wait a bit longer on the executor notification test

---

test_communication/CMakeLists.txt

This adds tests for all `message_files`.
Note: `rmw_connext_dynamic_cpp` test segfaults with `DynamicArrayPrimitives` message.

add tests for all message_files

---

test_communication/test/test_publisher.cpp
test_communication/test/test_publisher_subscriber.cpp
test_communication/test/test_requester.cpp

If test cycles start as infrequent as once per second that implies that after discovery finished the average wasted time is .5 seconds. And if multiple different messages in a cycle are then spaced out by 100ms that can add up to another .5 seconds (for five different messages, e.g. `DynamicArrayPrimitives`).
Since with all the matrix tests we run more than 220 tests in the `test_communication` package alone it makes sense to reduce the amount of wasted time per test as much as possible. Therefore this patch changes the timing to start new cycles at least 10 times per second and only use 10ms between different messages within one cycle. That should reduce the average time per test by .45 - .9 seconds on average. While not all tests are updated the majority of them are …

update test times

---

test_communication/test/test_requester.cpp
test_rclcpp/test/test_client_scope_client.cpp
test_rclcpp/test/test_client_wait_for_service_shutdown.cpp
test_rclcpp/test/test_executor.cpp
test_rclcpp/test/test_multiple_service_calls.cpp
test_rclcpp/test/test_multithreaded.cpp
test_rclcpp/test/test_services_client.cpp

With this patch Connext also sleeps since it doesn't implement `wait_for_service` yet (rather then failing these service tests).
Before: http://ci.ros2.org/job/ci_linux/1570/
After: http://ci.ros2.org/job/ci_linux/1571/

use sleep if wait_for_service throws

---

test_communication/test/test_requester.cpp

Revert / modify the timing changes form #144 for the `test_requester`. Since the variable `wait_between_services` does not do what it name implies but defines the timeout how long to wait for a response to arrive the shorter timing doesn't apply to it.
Before: http://ci.ros2.org/job/ci_linux/1589/testReport/(root)/test_requester_replier_cpp__Primitives__rmw_connext_cpp_/
After http://ci.ros2.org/job/ci_linux/1590/testReport/(root)/test_requester_replier_cpp__Primitives__rmw_connext_cpp_/
Please review.

revert test requester timing

---

test_communication/CMakeLists.txt

The Windows builds have ~150 skipped tests (http://ci.ros2.org/job/ci_windows/1572/testReport/). Simply because the executable is in the wrong location (http://ci.ros2.org/job/ci_windows/1572/testReport/(root)/projectroot/test_publisher_subscriber_cpp__rmw_connext_cpp__Empty/).
Additionally the `test_subscription_valid_data_cpp` test doesn't use any arguments but is being invoked with every message file in the package (http://ci.ros2.org/job/ci_windows/1572/testReport/(root)/projectroot/) which is 19 times per rmw impl.
Build with this patch http://ci.ros2.org/job/ci_windows/1580/testReport/(root)/projectroot/

remove duplicates of test_subscription_valid_data_cpp, fix skipped tests on Windows

---

test_rclcpp/test/test_local_parameters.cpp

While Windows warnings and errors have no priority anymore I think we should still use the appropriate types for the check here.
Before: http://ci.ros2.org/job/ci_windows/1589/warnings35Result/new/package.-1822083627/
After: http://ci.ros2.org/job/ci_windows/1593/

fix warnings on Windows

---

test_rclcpp/CMakeLists.txt

Fixes failing `gtest_multithreaded__rmw_connext_cpp` on linux, OS X and windows
http://ci.ros2.org/job/ci_linux/1628/
http://ci.ros2.org/job/ci_osx/1224/
http://ci.ros2.org/job/ci_windows/1594/

Allow more time for multithreaded tests

---

test_rclcpp/test/test_local_parameters.cpp

Avoid warnings shown in certain build configurations (e.g., http://ci.ros2.org/view/nightly/job/nightly_linux_release/129/warnings18Result/new/). I'll be out of contact for a while, so please merge without me.

init variables to avoid compiler warnings

---

test_rclcpp/test/test_remote_parameters.cpp

See: https://github.com/eProsima/ROS-RMW-Fast-RTPS-cpp/pull/51#issuecomment-242872096

add sleep to avoid client/server race until we have a better solution

---

test_communication/test/message_fixtures.hpp
test_communication/test/message_fixtures.py

This PR homogenize fixture between for cpp and python tests so that we can run multi rcl tests.
Note that char values are set to valid ASCII values the time we decide how to handle encoding.
Tests pass locally on opensplice and connext for all message types.
CI jobs:
- Linux:    [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=1718)](http://ci.ros2.org/job/ci_linux/1718)
- OSX:    [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=1283)](http://ci.ros2.org/job/ci_osx/1283)
- Windows:    [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=1639)](http://ci.ros2.org/job/ci_windows/1639)

Ascii fixture

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/test_client_scope_consistency_client.cpp
test_rclcpp/test/test_client_scope_consistency_server.cpp

Extends "remove blocks and workarounds on service tests" https://github.com/ros2/system_tests/pull/162, which has moved branches, to cover the newly-added client scope consistency tests
@wjwwood

Incorporate client consistency test into #162

---

test_communication/CMakeLists.txt
test_communication/test/publisher_py.py
test_communication/test/subscriber_py.py

this PR enables python tests for fastrtps now that c typesupport works for all message types.
Note: this PR also extends the maximum number of `spin_once` acceptable per test given that fastrtps calls  `rcl_take_with_info` several times per second even if no message is received. This required more investigation and will be addressed in a follow-up PR
Linux: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=1759)](http://ci.ros2.org/job/ci_linux/1759)
OSX: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=1308)](http://ci.ros2.org/job/ci_osx/1308/)
Windows: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=1680)](http://ci.ros2.org/job/ci_windows/1680/)

Enable python fastrtps

---

test_communication/test/message_fixtures.hpp
test_communication/test/service_fixtures.hpp
test_communication/test/test_subscription_valid_data.cpp
test_rclcpp/include/test_rclcpp/utils.hpp
test_rclcpp/test/parameter_fixtures.hpp
test_rclcpp/test/test_executor.cpp
test_rclcpp/test/test_intra_process.cpp
test_rclcpp/test/test_local_parameters.cpp
test_rclcpp/test/test_multiple_service_calls.cpp
test_rclcpp/test/test_multithreaded.cpp
test_rclcpp/test/test_parameters_server.cpp
test_rclcpp/test/test_remote_parameters.cpp
test_rclcpp/test/test_repeated_publisher_subscriber.cpp
test_rclcpp/test/test_services_client.cpp
test_rclcpp/test/test_services_server.cpp
test_rclcpp/test/test_spin.cpp
test_rclcpp/test/test_subscription.cpp

Update style to pass new cpplint check (ament/ament_lint#59).
http://ci.ros2.org/job/ci_linux/1763/

comply with stricter cpplint rules

---

test_rclcpp/CMakeLists.txt

Consistent naming when using CMake variable for rmw implementation

---

test_communication/test/publisher_py.py
test_communication/test/subscriber_py.py

Remove unused module since https://github.com/ros2/system_tests/pull/152/commits/55d6d75f2684f78d3ae17b508ac1c4bbeba893c8
should fix: http://ci.ros2.org/job/ci_windows/1806/testReport/junit/test_communication/pyflakes/UnusedImport__test_publisher_py_py_29_/

fix pyflakes

---

test_communication/test/service_fixtures.hpp
test_communication/test/service_fixtures.py

Extend test suite to test strings longer than 256 for services. This relies on https://github.com/ros2/rmw_fastrtps/issues/71

test loong strings for services

---

test_communication/test/publisher_py.py
test_communication/test/subscriber_py.py

Publishers in python and c++ don't wait the same time between messages and message bursts.
This PR makes them have the same behavior e.g. send message burst every 100ms and stop publishing after 10s.
Can't say for sure that it reduce the number of failing/flaky pub/sub tests but will at least help to narrow it down.
Should also prevent test to timeout with missing results

rclpy tests match rclcpp timing

---

test_communication/CMakeLists.txt
test_communication/package.xml

When implementing tests for `rostopic_echo_py` (https://github.com/ros2/cli_tools/pull/5), I had need of a bunch of messages to push through the YAML and CSV converters. This PR installs the messages and related fixtures so that they can be used in testing other packages.
http://ci.ros2.org/job/ci_linux/2314/
http://ci.ros2.org/job/ci_osx/1769/
http://ci.ros2.org/job/ci_windows/2343/

Install msgs and fixtures for use by other packages

---

test_communication/package.xml

`test_communication` fixtures need `builtin_interfaces`. Unveiled by `cli_tools/test_primitives` using these for testing.
This should fix the failing `cli_tools/test_primitives` test on all nightlies: e.g http://ci.ros2.org/view/nightly/job/nightly_linux_release/lastSuccessfulBuild/testReport/(root)/test_primitives/test_primitives/

Add missing exec dep on builtin_interfaces

---

test_rclcpp/test/test_multithreaded.cpp

This PR addresses failures that have come up since we started running on 96-core ARM servers:
* In general, cap the internal test parallelism at 16, independent of how many cores the machine has.
* In one case, adjust the spin_until logic to wait for *all* futures to complete instead of waiting for just one (the old behavior is presumably reliable for a low level of parallelism, but it's not when you go wide).
* In one case, adjust the subscriber-side queue length to accommodate the expected number of messages (again, the old behavior is presumably reliable for low parallelism).

Fix tests for many core machines

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/pub_sub_fixtures.hpp
test_rclcpp/test/test_avoid_ros_namespace_conventions_qos.cpp
test_rclcpp/test/test_client_scope_consistency_client.cpp
test_rclcpp/test/test_client_scope_consistency_server.cpp
test_rclcpp/test/test_subscription.cpp

New test based on @dhood's suggestion. This should be enough to put the rest of the connected pr's in review without waiting to refactor topic names and types.
Connects to ros2/rmw#106

add test for avoid_ros_namespace_conventions qos

---

test_communication/CMakeLists.txt

This creates and run the security tests only if `-DSECURITY=ON` is passed to cmake

add option for security tests

---

test_communication/test/replier_py.py
test_communication/test/requester_py.py
test_communication/test/subscriber_py.py

Right now all tests involving rclpy exit gracefully on success (see trace below), this cleans up the nodes before shutting down rcl.
*before:*
```
subscriber: beginning loop
received message #1 of 4
spin_count: 2
received message #2 of 4
spin_count: 3
received message #3 of 4
spin_count: 4
received message #4 of 4
spin_count: 5
>>> [rcutils|error_handling.c:148] rcutils_set_error_state()
This error state is being overwritten:
'rcl node is invalid, rcl instance id does not match, at /home/mikael/work/tb2_beta2_ws/src/ros2/rcl/rcl/src/rcl/node.c:346'
with this new error message:
'node handle is null'
rcutils_reset_error() should be called after error handling to avoid this.
<<<
Exception ignored in: <bound method Node.__del__ of <rclpy.node.Node object at 0x7fb0ae8a4d30>>
Traceback (most …
```

destroy node before shutdown

---

test_communication/test/message_fixtures.hpp
test_communication/test/message_fixtures.py

This is mostly to make sure that we don't rely on the magic 101 [here](https://github.com/ros2/rmw_fastrtps/blob/8623ccde0fbdeab8142ed4062978c977446327f0/rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.hpp#L772) or any other arbitrary limitation on arrays
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2976)](http://ci.ros2.org/job/ci_linux/2976/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=415)](http://ci.ros2.org/job/ci_linux-aarch64/415/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2405)](http://ci.ros2.org/job/ci_osx/2405/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3085)](http://ci.ros2.org/job/ci_windows/3085/)

testing array longers than 101

---

test_rclcpp/test/test_multithreaded.cpp

Together with ros2/rclcpp#355 this fixes the flakyness of the `test_multithreaded` tests (see ros2/build_cop#41). The "highlights" of this patch:
* create subscribers and wait for them before publishing messages
* remove logic to abort executor based on past time - CTest will take care of it in case the test would hang
* increase queue size to hold all published messages
These CI builds don't include the fix in `rclcpp`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2985)](http://ci.ros2.org/job/ci_linux/2985/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=421)](http://ci.ros2.org/job/ci_linux-aarch64/421/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2411)](http://ci.ros2.o …

fix flaky multi-threaded test

---

test_communication/test/test_publisher_subscriber.py.in
test_communication/test/test_requester_replier.py.in
test_communication/test/test_secure_publisher_subscriber.py.in

This ensures that the output of the Python executables is visible when something goes south. That avoids speculations around why a test might have failed (see `test_publisher_subscriber__Nested__rclpy__rmw_fastrtps_cpp_.test_publisher_subscriber` in ros2/build_cop#41).
I don't plan to run CI for this simple change.

use unbuffered Python in launch files

---

test_communication/test/test_publisher.cpp
test_communication/test/test_publisher_subscriber.cpp
test_communication/test/test_replier.cpp
test_communication/test/test_secure_publisher.cpp
test_communication/test/test_secure_subscriber.cpp
test_communication/test/test_subscriber.cpp
test_communication/test/test_subscription_valid_data.cpp
test_rclcpp/test/test_client_scope_consistency_server.cpp
test_rclcpp/test/test_client_scope_server.cpp
test_rclcpp/test/test_parameters_server.cpp
test_rclcpp/test/test_services_server.cpp

this should fix flaky tests like http://ci.ros2.org/view/nightly/job/nightly_osx_repeated/771/testReport/junit/(root)/projectroot/test_client_scope_consistency_cpp__rmw_connext_cpp/ (referenced in https://github.com/ros2/build_cop/issues/41) which sometimes don't respond to SIGINT and are then sent SIGTERM:
```
...
[test_client_scope_consistency_client_cpp] received second result
[test_client_scope_consistency_client_cpp] received correct result
[test_client_scope_consistency_client_cpp] destroying second client
[test_client_scope_consistency_client_cpp] [       OK ] service_client__.client_scope_consistency_regression_test (3520 ms)
[test_client_scope_consistency_client_cpp] [----------] 1 test from service_client__ (3520 ms total)
[test_client_scope_consistency_client_cpp] …
```

Ensure nodes have called rclcpp::shutdown before exiting

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/parameter_fixtures.hpp
test_rclcpp/test/test_local_parameters.cpp
test_rclcpp/test/test_remote_parameters.cpp

connects to ros2/rclcpp#356 
I don't think it's necessary to do any waiting [when calling node->set_parameters](https://github.com/ros2/system_tests/blob/67efe8e319b997c389c266d9ac237b850807ba4e/test_rclcpp/test/test_local_parameters.cpp#L351) because FWIU there are no service calls involved (correct me if I'm wrong).
Also, now that we wait in so many places, the timeout has to be increased significantly (15 waits of 20s)
CI including other branches that add the implementation of wait_for_service and use it in demos:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3001)](http://ci.ros2.org/job/ci_linux/3001/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=428)](http://ci.ros2.org/job/ci_linux-aarch64/428/)
* …

Use wait_for_service after creating parameters_client

---

test_communication/CMakeLists.txt

ros2/rclcpp#219 doesn't seem to be a problem with OpenSplice 6.7 anymore: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3118)](http://ci.ros2.org/job/ci_linux/3118/)

reenable array tests with OpenSplice

---

test_communication/test/test_requester.cpp
test_rclcpp/test/test_avoid_ros_namespace_conventions_qos.cpp
test_rclcpp/test/test_client_scope_client.cpp
test_rclcpp/test/test_client_scope_consistency_client.cpp
test_rclcpp/test/test_executor.cpp
test_rclcpp/test/test_intra_process.cpp
test_rclcpp/test/test_local_parameters.cpp
test_rclcpp/test/test_multiple_service_calls.cpp
test_rclcpp/test/test_multithreaded.cpp
test_rclcpp/test/test_publisher.cpp
test_rclcpp/test/test_remote_parameters.cpp
test_rclcpp/test/test_repeated_publisher_subscriber.cpp
test_rclcpp/test/test_services_client.cpp
test_rclcpp/test/test_services_in_constructor.cpp
test_rclcpp/test/test_spin.cpp
test_rclcpp/test/test_subscription.cpp
test_rclcpp/test/test_timeout_subscriber.cpp
test_rclcpp/test/test_timer.cpp

follow up of https://github.com/ros2/system_tests/pull/220
redo of the [shutdown](https://github.com/ros2/system_tests/tree/shutdown) stale branch
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3155)](http://ci.ros2.org/job/ci_linux/3155/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=496)](http://ci.ros2.org/job/ci_linux-aarch64/496/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2512)](http://ci.ros2.org/job/ci_osx/2512/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3207)](http://ci.ros2.org/job/ci_windows/3207/)

call rclcpp::shutdown in all tests

---

test_rclcpp/test/test_local_parameters.cpp

restore full name to confirm https://github.com/ros2/rmw_connext/issues/193 is fixed
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3173)](http://ci.ros2.org/job/ci_linux/3173/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=514)](http://ci.ros2.org/job/ci_linux-aarch64/514/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2539)](http://ci.ros2.org/job/ci_osx/2539/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3235)](http://ci.ros2.org/job/ci_windows/3235/)

revert hack shortening node name

---

test_rclcpp/test/parameter_fixtures.hpp

This reverts commit 8e9d767891e4e619b2bbfbd4dac5e6fffafd84bc.
Connects to ros2/rclcpp#372

Revert "apply forward slash for list_parameters (#224)"

---

test_communication/CMakeLists.txt

no need to tweak python path now that messages come from test_msgs.
Not setting the working directory should allow a cleaner test display on jenkins and the test_communication tests will not show up under rosidl_generator_py anymore (e.g. http://ci.ros2.org/view/nightly/job/nightly_osx_repeated/lastCompletedBuild/testReport/projectroot/rosidl_generator_py/)
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3281)](http://ci.ros2.org/job/ci_linux/3281/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=558)](http://ci.ros2.org/job/ci_linux-aarch64/558/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2614)](http://ci.ros2.org/job/ci_osx/2614/)
* Windows [![Build …

remove unnecessary working_dir and pythonpath tweaks

---

test_communication/test/subscriber_py.py

This fixes ros2/build_cop#59, a test failure on windows debug. It does so by minimizing the number of calls to `__repr__()` on a message instance.
The test failed because the python subscriber is too slow to consume messages. The 5th message in the subscriber's queue is overwritten before the subscriber can take it. cProfile shows the subscriber spends on average 0.068s cumulative in `__repr__` calls per call to `listener_cb` on windows debug. The messages are published 0.02s apart on average, so the subscriber queue is being overwhelmed.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3310)](http://ci.ros2.org/job/ci_linux/3310/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=575)](http://ci.ros2.org/job/ci_l …

Minimize the number of calls to message.__repr__()

---

test_communication/CMakeLists.txt
test_rclcpp/CMakeLists.txt

When cleaning up some cmake I wondered if passing /bigobj on windows is still necessary. CI seems happy without it. Maybe the new version of VS/MSVC behaves differently? (looks like this was added [2 years ago](https://github.com/ros2/system_tests/pull/35))
@wjwwood do you think it's safe to remove this ?
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3375)](http://ci.ros2.org/job/ci_windows/3375/)

removing /bigobj that doesnt seem to be necessary anymore

---

test_communication/test/test_publisher.cpp
test_communication/test/test_publisher_subscriber.cpp
test_communication/test/test_replier.cpp
test_communication/test/test_requester.cpp
test_communication/test/test_subscriber.cpp
test_communication/test/test_subscription_valid_data.cpp
test_rclcpp/test/test_timeout_subscriber.cpp
test_security/test/test_secure_publisher.cpp

follow up of https://github.com/ros2/system_tests/pull/230#discussion_r144608837
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3336)](http://ci.ros2.org/job/ci_linux/3336/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=596)](http://ci.ros2.org/job/ci_linux-aarch64/596/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2666)](http://ci.ros2.org/job/ci_osx/2666/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3385)](http://ci.ros2.org/job/ci_windows/3385/) (unrelated test failure)

Replaces "std::cout<<" with "printf"

---

test_communication/CMakeLists.txt
test_security/CMakeLists.txt

Looks like #239 broke master on windows Debug. This passes again `/bigobj` for the 2 packages that need it
* Windows Release [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3394)](http://ci.ros2.org/job/ci_windows/3394/) 
* Windows Debug [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3395)](http://ci.ros2.org/job/ci_windows/3395/)
* Windows RelWithDebInfo [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3392)](http://ci.ros2.org/job/ci_windows/3392/)

Restore bigobj

---

test_security/test/test_secure_publisher.cpp
test_security/test/test_secure_publisher_subscriber.py.in
test_security/test/test_secure_subscriber.cpp

Aimed at fixing #242 (but it's not certain that cross-talk was causing the issue)
Standard CI on only testing `test_security` package:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3342)](http://ci.ros2.org/job/ci_linux/3342/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=601)](http://ci.ros2.org/job/ci_linux-aarch64/601/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2676)](http://ci.ros2.org/job/ci_osx/2676/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3398)](http://ci.ros2.org/job/ci_windows/3398/)
This build repeatedly tests them 84 times without failure: http://ci.ros2.org/job/ci_osx/2674/ (at which point the buildfarm machine …

Add namespace to avoid crosstalk in security 'no connection' tests

---

test_communication/CMakeLists.txt
test_security/CMakeLists.txt

find gtest before macro invocation so that its not found at each macro invocation
similar to ros2/rcl#177
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3599)](http://ci.ros2.org/job/ci_linux/3599/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=790)](http://ci.ros2.org/job/ci_linux-aarch64/790/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2937)](http://ci.ros2.org/job/ci_osx/2937/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3689)](http://ci.ros2.org/job/ci_windows/3689/) (unrelated timing failures)

Find gtest only once

---

test_security/CMakeLists.txt

Move logic adding openssl libraries to `DYLD_LIBRARY_PATH` from the ci script into this package (the only one using connext security)
connects to ros2/ci#112

use brew to find openssl library path and add it to the library dirs

---

test_communication/CMakeLists.txt
test_rclcpp/CMakeLists.txt
test_security/CMakeLists.txt

This is needed to support cmake 3.10. We could define the policy based on the version of CMake but I preferred updating the codebase to have something compliant with all cmake versions without relying on undefined behavior.
More details at https://cmake.org/cmake/help/git-stage/policy/CMP0070.html
Example of CMake warning without this patch:
```
Policy CMP0070 is not set: Define file(GENERATE) behavior for relative
paths.  Run "cmake --help-policy CMP0070" for policy details.  Use the
cmake_policy command to set the policy and suppress this warning.
file(GENERATE) given relative OUTPUT path:
test/test_services__rmw_connext_cpp_RelWithDebInfo.py
This is not defined behavior unless CMP0070 is set to NEW.  For
compatibility with older versions of CMake, the previous undefined behavior
will …
```

cmake 3.10 compatibility: pass absolute path to file(GENERATE) function

---

test_rclcpp/test/test_multiple_service_calls.cpp

Connects to ros2/rclcpp#415
Without ros2/rclcpp#415 the client can't send the second service call because it deadlocks trying to lock the internal mutex.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3697)](http://ci.ros2.org/job/ci_linux/3697/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=863)](http://ci.ros2.org/job/ci_linux-aarch64/863/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3034)](http://ci.ros2.org/job/ci_osx/3034/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3795)](http://ci.ros2.org/job/ci_windows/3795/)

Add regression test for recursive service calls

---

test_rclcpp/test/test_local_parameters.cpp

Connects to ros2/rclcpp#414
Regression test for https://github.com/ros2/rclcpp/pull/414
Without https://github.com/ros2/rclcpp/pull/414, the test will crash (I'm getting `C++ exception with description "std::bad_alloc" thrown in the test body.` but in https://github.com/ros2/demos/pull/203/files#diff-a5a151889abb3214250ba9db05358e4bR92 it would segfault).
CI including ros2/rclcpp#414
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3695)](http://ci.ros2.org/job/ci_linux/3695/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=862)](http://ci.ros2.org/job/ci_linux-aarch64/862/)
* macOS skipped because queue is busy
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3799 …

Regression test for set_parameters with bad callback reference

---

test_communication/test/test_publisher_subscriber.cpp
test_communication/test/test_replier.cpp
test_communication/test/test_subscriber.cpp
test_rclcpp/include/test_rclcpp/utils.hpp
test_rclcpp/test/parameter_fixtures.hpp
test_rclcpp/test/test_client_scope_client.cpp
test_rclcpp/test/test_client_scope_consistency_client.cpp
test_rclcpp/test/test_client_scope_consistency_server.cpp
test_rclcpp/test/test_client_scope_server.cpp
test_rclcpp/test/test_client_wait_for_service_shutdown.cpp
test_rclcpp/test/test_local_parameters.cpp
test_rclcpp/test/test_multiple_service_calls.cpp
test_rclcpp/test/test_multithreaded.cpp
test_rclcpp/test/test_parameters_server.cpp
test_rclcpp/test/test_remote_parameters.cpp
test_rclcpp/test/test_services_client.cpp
test_rclcpp/test/test_services_in_constructor.cpp
test_rclcpp/test/test_spin.cpp
test_rclcpp/test/test_timer.cpp
test_security/test/test_secure_publisher.cpp
test_security/test/test_secure_subscriber.cpp

Update for rclcpp namespace removals

---

test_communication/CMakeLists.txt

Should not be merged before #244 as there is a potential for flakiness without wait_for_service is available (although all tests passed first run in this particular job).
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3704)](http://ci.ros2.org/job/ci_windows/3704/)

reenable Windows service tests: rclcpp requester <=> rclpy replier 

---

test_communication/CMakeLists.txt
test_communication/test/replier_py.py

We actually have C/python service support for Fast-RTPS, Connext and Opensplice.
The only rmw implementationl not supporting C/Python services is connext_dynamic.
This PR reenables tests for connext. This should not be merged before #244 
The last commit is a workaround for testing as connext startup is too slow and #244 is not merged yet.
Job with only Fast-RTPS and Opensplice:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3620)](http://ci.ros2.org/job/ci_linux/3620/)
Job with only Fast-RTPS and Connext:
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3713)](http://ci.ros2.org/job/ci_windows/3713/)

Skip python service tests only for connext dynamic

---

test_communication/test/publisher_py.py
test_communication/test/replier_py.py
test_communication/test/requester_py.py
test_communication/test/subscriber_py.py
test_communication/test/test_publisher.cpp
test_communication/test/test_publisher_subscriber.py.in
test_communication/test/test_replier.cpp
test_communication/test/test_requester.cpp
test_communication/test/test_requester_replier.py.in
test_communication/test/test_subscriber.cpp
test_security/test/test_secure_publisher_subscriber.py.in

equivalent of #243 for test_communication
This adds unique namespace to all nodes pub/sub nodes as well as add slashes to the topic / service names.
This will regression test https://github.com/ros2/rmw_opensplice/issues/220 as well as making sure to avoid cross talk when repeating tests.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3780)](http://ci.ros2.org/job/ci_linux/3780/) (incudes linter fix commit)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=918)](http://ci.ros2.org/job/ci_linux-aarch64/918/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3116)](http://ci.ros2.org/job/ci_osx/3116/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=38 …

[test_communication] Unique namespaces

---

test_rclcpp/CMakeLists.txt

Fixes https://github.com/ros2/system_tests/issues/212
Linux CI with `ament_test_args: --only test_rclcpp --retest-until-fail 150 --ctest-args -R client_scope`: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4030)](https://ci.ros2.org/job/ci_linux/4030/)

Longer timeout for tests with two clients

---

test_communication/test/requester_py.py

Changes requester_py.py to use new client api
Connects to ros2/rclpy#170

Use updated rclpy client api

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/node_name_list.cpp
test_rclcpp/test/node_with_name.cpp
test_rclcpp/test/test_two_executables.py.in

add unit test to check for node names across rmw impl.

---

test_communication/test/test_messages_c.cpp

This fixes a [gcc warning](https://ci.ros2.org/job/ci_packaging_linux/92/warnings23Result/package.-1552620408/) as the string to store can be up to 4 numeric characters + the null-terminator so the container should be of size 5.
related to https://github.com/ros2/ros2/issues/481

account for null-terminator character

---

test_rclcpp/test/test_local_parameters.cpp
test_rclcpp/test/test_parameters_server.cpp

Removes code that was manually starting the parameter service.
Connects to ros2/rclcpp#478

Parameter services automatically start

---

test_rclcpp/test/parameter_fixtures.hpp
test_rclcpp/test/test_local_parameters.cpp

Split ParameterVariant

---

test_cli_remapping/CMakeLists.txt
test_cli_remapping/package.xml
test_cli_remapping/test/name_maker.cpp
test_cli_remapping/test/name_maker.py
test_cli_remapping/test/test_cli_remapping.py

Adds a new package `test_cli_remapping` that checks if command line remapping arguments passed to a process result in changes to the names it uses.

Add tests for command line remapping

---

test_rclcpp/test/test_multithreaded.cpp

~~Needs to be targeted at master after #271 is merged.~~ Targeted at master
connects to ros2/rclcpp#486

Pass initial parameter values to node constructor

---

test_cli_remapping/test/test_cli_remapping.py

follow up of https://github.com/ros2/launch/pull/73
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4546)](http://ci.ros2.org/job/ci_linux/4546/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1459)](http://ci.ros2.org/job/ci_linux-aarch64/1459/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3733)](http://ci.ros2.org/job/ci_osx/3733/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=4621)](http://ci.ros2.org/job/ci_windows/4621/)

use new launch legacy namespace

---

test_rclcpp/test/parameter_fixtures.hpp

connects to ros2/rclcpp#490
This fixes the test expectations about parameters that don't exist but were queried by `parameters_client->get_parameters(..)`

Get parameters that aren't set should have type NOT_SET

---

test_security/package.xml

Just commenting out the unused dependency for now.
Once https://github.com/ros2/system_tests/blob/0975759086d0101c2e6227dd0668995795371a1b/test_security/test/test_secure_publisher_subscriber.py.in#L27 is answered we can either remove the commented code or enable multi client library testing. As we currently don't have the same default node behavior in C++ and Python, it may be worth testing both.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4576)](http://ci.ros2.org/job/ci_linux/4576/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1487)](http://ci.ros2.org/job/ci_linux-aarch64/1487/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3763)](http://ci.ros2.org/job/ci_osx/3763/)
* …

comment out currently unused rclpy dependency

---

test_rclcpp/test/parameter_fixtures.hpp
test_rclcpp/test/test_remote_parameters.cpp

Connects to ros2/rclcpp#494
leaving in progress until ci comes back green

add test for set_parameters_atomically

---

test_cli/CMakeLists.txt
test_cli/package.xml
test_cli_remapping/CMakeLists.txt
test_cli_remapping/package.xml
test_communication/CMakeLists.txt
test_communication/package.xml

Copies the logic from `test_communication` to use the debug python executable on windows when appropriate.
CI just windows debug [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=4686)](https://ci.ros2.org/job/ci_windows/4686/)
context
* https://github.com/ros2/system_tests/pull/268#issuecomment-396023023
* https://github.com/ros2/system_tests/pull/274#issuecomment-396023045

Use debug python executable on windows

---

test_communication/CMakeLists.txt
test_communication/test/test_message_serialization.cpp
test_communication/test/test_publisher_subscriber_raw.cpp
test_communication/test/test_publisher_subscriber_serialized.cpp
test_rclcpp/test/test_multithreaded.cpp
test_rclcpp/test/test_spin.cpp
test_rclcpp/test/test_subscription.cpp

Expose cdr

---

test_communication/package.xml

this is not required since Builtins.msg has been moved to the test_msgs package https://github.com/ros2/system_tests/pull/223
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4860)](http://ci.ros2.org/job/ci_linux/4860/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1713)](http://ci.ros2.org/job/ci_linux-aarch64/1713/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=4049)](http://ci.ros2.org/job/ci_osx/4049/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=4909)](http://ci.ros2.org/job/ci_windows/4909/)

remove unused builtin_interfaces dependency

---

test_security/CMakeLists.txt

Skips the linter introduced in ament/ament_lint#104 for now.

disable xmllint for now

---

test_security/CMakeLists.txt

Related to ros2/rmw_fastrtps#218.

match rmw_fastrtps_dynamic_cpp / rmw_connext_dynamic_cpp

---

test_communication/test/test_messages_c.cpp

Use consolidated rcl_wait_set_clear()

---

test_cli/CMakeLists.txt
test_cli/test/initial_params.py
test_cli/test/test_params_yaml.py
test_cli/test/utils.py

Adds an rclpy node to the test fixtures so that our tests cover both client libraries.
For these tests to succeed they must be run along with https://github.com/ros2/rclpy/pull/225
Connects to ros2/rclpy#202

Test parameter behavior for rclpy nodes

---

test_rclcpp/test/test_avoid_ros_namespace_conventions_qos.cpp
test_rclcpp/test/test_client_scope_consistency_client.cpp
test_rclcpp/test/test_executor.cpp
test_rclcpp/test/test_multiple_service_calls.cpp

This PR fixes some warnings that are being thrown by MacOS High Sierra and later.
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=5270)](http://ci.ros2.org/job/ci_linux/5270/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=2026)](http://ci.ros2.org/job/ci_linux-aarch64/2026/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=4386)](http://ci.ros2.org/job/ci_osx/4386/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=5249)](http://ci.ros2.org/job/ci_windows/5249/)

Fix warnings

---

test_communication/test/test_publisher.cpp
test_communication/test/test_publisher_subscriber.cpp
test_communication/test/test_subscriber.cpp

This resolves CI failures introduced by #43.
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=5361)](http://ci.ros2.org/job/ci_linux/5361/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=2088)](http://ci.ros2.org/job/ci_linux-aarch64/2088/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=4451)](http://ci.ros2.org/job/ci_osx/4451/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=5321)](http://ci.ros2.org/job/ci_windows/5321/)

Add new test message type DynamicArrayStaticArrayPrimitivesNested

---

test_communication/CMakeLists.txt
test_security/CMakeLists.txt

Connected to ros2/rosidl#301. This pull request tweaks `test_communication` and `test_security` packages to properly handle .msg and .srv definition in action folders.

Handles msg files with the same name in different subfolders

---

test_security/test/test_secure_publisher_subscriber.py.in

Given the FQN is used to lookup security artifacts from secure root directory, timestamping tests via the node's namespace is no longer directly appropriate.
Context:
https://github.com/ros2/rcl/pull/300
https://github.com/ros2/rcutils/pull/119

Adjusting namespace for security tests

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/test_waitable.cpp

Test for C++ waitable with a timer.
Currently test fails (`is_ready()` returns True, but `execute()` is never called)
connects to ros2/rclcpp#589

Add test for waitable

---

test_communication/CMakeLists.txt

Just temporarily for the Crystal release until we can figure out why they no longer communicate.

disable cross vendor tests for pub/sub fastrtps/connext

---

test_communication/CMakeLists.txt

Builds are actually failing for all cross-vendor tests involving rmw_fastrtps_cpp not just those between Connext and Fast-RTPS.

Disable any cross-vendor communication tests for Fast-RTPS.

---

test_rclcpp/test/node_with_name.cpp

This should fix for ros2/build_cop#153 by ignoring `RCLError` raised in the node constructor.
When `node_with_name` is connext and `node_name_list` is fastrtps the listing node can start, see the node name it expects, and exit before `node_with_name` finishes constructing itself. The test sends `SIGINT` to `node_with_name` which shutsdown the context. That causes checks to fail when creating services/clients/etc in the node constructor for parameters and the time source.

Ignore RCLError during Node constructor

---

test_rclcpp/test/node_with_name.cpp

Fixes a linter error introduced by ros2/system_tests#325
CI Linux testing `test_rclcpp` [![Build Status](https://ci.ros2.org/job/ci_linux/6065/badge/icon)](https://ci.ros2.org/job/ci_linux/6065/)

Remove unnecessary semicolon

---

test_communication/test/test_action_client.cpp
test_communication/test/test_action_server.cpp

connects to ros2/rosidl#348
CI at ros2/rosidl_typesupport#44
requires ros2/rcl_interfaces#62
This PR should be backported to crystal

Add test for test_msgs/NestedMessage.action

---

test_cli_remapping/package.xml
test_cli_remapping/test/test_cli_remapping.py
test_communication/package.xml
test_communication/test/test_action_client_server.py.in
test_communication/test/test_publisher_subscriber.py.in
test_communication/test/test_requester_replier.py.in
test_rclcpp/CMakeLists.txt
test_rclcpp/package.xml
test_rclcpp/test/test_executable_output.py.in
test_rclcpp/test/test_n_nodes.py.in
test_rclcpp/test/test_two_executables.py.in
test_security/package.xml
test_security/test/test_secure_publisher_subscriber.py.in

Connected to ros2/launch#159. Drops legacy launch API usage in `test_cli_remapping` package tests.

Drops legacy launch API usage.

---

test_communication/CMakeLists.txt
test_communication/test/action_client_py.py
test_communication/test/action_server_py.py

Resolves #332 
I more or less mimic'd the structure of the rclcpp Action tests.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6323)](http://ci.ros2.org/job/ci_linux/6323/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=2737)](http://ci.ros2.org/job/ci_linux-aarch64/2737/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=5205)](http://ci.ros2.org/job/ci_osx/5205/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=6173)](http://ci.ros2.org/job/ci_windows/6173/)

Add communication tests for Python Actions

---

test_communication/test/action_client_py.py
test_communication/test/test_action_client.cpp
test_communication/test/test_action_server.cpp
test_communication/test/test_messages_c.cpp

Connected to ros2/rosidl#334.
`char` in `.msg` files has a value range of `[0, 255]` according to the ROS 1 docs. Therefore it is being mapped to `uint8` according to https://github.com/ros2/design/blob/gh-pages/articles/143_legacy_interface_definition.md#mapping-to-idl-types

update char type mapping, update to use separated action types

---

test_communication/CMakeLists.txt
test_communication/test/test_action_client_server.py.in
test_communication/test/test_publisher_subscriber.py.in
test_communication/test/test_requester_replier.py.in

This reduced the CMake configure time of `test_communication` from ~15 min to ~2.5 min (times with Connext, FastRTPS and OpenSplice). Instead of generating ~1150 separate Python files each with one test a single Python test file is being generated per group and the test is being invoked with each message/service/action as a parameter.
Note the different number of tests:
Before: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6359)](https://ci.ros2.org/job/ci_linux/6359/)
After: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6365)](https://ci.ros2.org/job/ci_linux/6365/)

refactor test generation

---

test_cli/package.xml
test_cli_remapping/package.xml
test_communication/package.xml
test_rclcpp/package.xml
test_security/package.xml

This commit should be fast-forwarded onto the crystal branch rather than squashed.
Since we don't do bloom releases for system_tests our release discipline has lapsed. There's a 0.6.0 tag for crystal but the package.xml version was never updated. This jumps them from 0.4.0 to 0.6.1 to enable backporting of test fixes.

Prepare 0.6.1

---

test_cli/test/test_params_yaml.py

Related to ros2/rosidl_python#35.
https://ci.ros2.org/view/nightly/job/nightly_osx_debug/1202/testReport/test_cli.test/test_params_yaml/test_integer_array_params__Users_osrf_jenkins_agent_workspace_nightly_osx_debug_ws_src_ros2_system_tests_test_cli_test_initial_params_py_/
I just ran the test locally confirming it passed with the patch.

fixes a failing test introduced by the switch to array.array

---

test_rclcpp/test/test_client_scope_consistency_client.cpp
test_rclcpp/test/test_client_scope_consistency_server.cpp

Some new fields are being added to rmw_qos_profile_t, and this package needs to be updated to be compatible with the newer definition of the struct.
Connects to ros2/rmw#173

Update to be compatible with new rmw_qos_profile_t

---

test_communication/test/action_server_py.py
test_communication/test/test_action_server.cpp

Now using active verbs as described in the design doc:
http://design.ros2.org/articles/actions.html#goal-states
Connects to ros2/rcl#399.
Signed-off-by: Jacob Perron <jacob@openrobotics.org>

Rename action state transitions

---

test_communication/test/test_action_client.cpp

It now takes callbacks for the goal response and result.
Connects to ros2/rclcpp#635

Update call to async_send_goal

---

test_cli_remapping/CMakeLists.txt
test_cli_remapping/package.xml
test_cli_remapping/test/test_cli_remapping.py
test_communication/CMakeLists.txt
test_communication/package.xml
test_communication/test/test_action_client_server.py.in
test_communication/test/test_publisher_subscriber.py.in
test_communication/test/test_requester_replier.py.in
test_rclcpp/CMakeLists.txt
test_rclcpp/package.xml
test_rclcpp/test/test_executable_output.py.in
test_rclcpp/test/test_n_nodes.py.in
test_rclcpp/test/test_two_executables.py.in
test_security/CMakeLists.txt
test_security/package.xml
test_security/test/test_secure_publisher_subscriber.py.in

Migrate launch tests to new launch_testing features & API

---

test_communication/msg/FieldsWithSameType.msg
test_communication/test/test_message_serialization.cpp
test_communication/test/test_messages_c.cpp
test_communication/test/test_publisher.cpp
test_communication/test/test_publisher_subscriber.cpp
test_communication/test/test_publisher_subscriber_serialized.cpp
test_communication/test/test_replier.cpp
test_communication/test/test_requester.cpp
test_communication/test/test_subscriber.cpp
test_security/test/test_secure_publisher.cpp
test_security/test/test_secure_subscriber.cpp

Interface definitions for testing have been consolidated into a common package, [test_interface_files](https://github.com/ros2/test_interface_files).
They have been refactored in an effort to reduce the number of interfaces and also renamed to follow IDL terminology.
This change switches over the tests to use the new interface definitions.
Connects to https://github.com/ros2/rcl_interfaces/issues/58

Use new interface definitions

---

test_communication/CMakeLists.txt

See ros2/rosidl_typesupport_opensplice#27.
Linux `test_communication` with 3 RMW impl.: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6947)](https://ci.ros2.org/job/ci_linux/6947/)

skip cross vendor testing of OpenSplice for WStrings

---

test_communication/test/test_messages_c.cpp

- Initialize BasicTypes field of Arrays
- Correct the number of BoundedSequences messages
- Add C message tests for Constants.msg, Defaults.msg, and Empty.msg

Fix issues with C messages test

---

test_rclcpp/CMakeLists.txt

See ros2/ros2#658.
Unnecessary usage of `target_include_directories` and `target_link_libraries` with gtest macros here.

Delete unnecessary usage of target_include_directories and target_link_libraries with gtest macros

---

test_communication/test/test_publisher.cpp
test_communication/test/test_publisher_subscriber.cpp
test_communication/test/test_publisher_subscriber_serialized.cpp
test_communication/test/test_subscription_valid_data.cpp
test_rclcpp/test/pub_sub_fixtures.hpp
test_rclcpp/test/test_avoid_ros_namespace_conventions_qos.cpp
test_rclcpp/test/test_intra_process.cpp
test_rclcpp/test/test_multithreaded.cpp
test_rclcpp/test/test_publisher.cpp
test_rclcpp/test/test_repeated_publisher_subscriber.cpp
test_rclcpp/test/test_spin.cpp
test_rclcpp/test/test_subscription.cpp
test_security/test/test_secure_publisher.cpp

Corrected publish calls with shared_ptr signature

---

test_communication/test/test_action_client_server.py.in
test_communication/test/test_publisher_subscriber.py.in
test_communication/test/test_requester_replier.py.in
test_rclcpp/test/test_n_nodes.py.in
test_rclcpp/test/test_two_executables.py.in
test_security/test/test_secure_publisher_subscriber.py.in

Follow-up of https://github.com/ros2/system_tests/pull/340.

Handle launch_testing assertExitCodes correctly

---

test_rclcpp/test/parameter_fixtures.hpp
test_rclcpp/test/test_local_parameters.cpp
test_rclcpp/test/test_parameters_server.cpp
test_rclcpp/test/test_remote_parameters.cpp
test_rclcpp/test/test_two_executables.py.in

Related to https://github.com/ros2/rclcpp/issues/705
In particular, added tests for attempting to set undeclared parameters.

Improve tests for parameters

---

test_communication/test/test_message_serialization.cpp
test_communication/test/test_messages_c.cpp

Fix memory leaks detected by AddressSanitizer in
test_message_serialization and test_messages_c tests.
Signed-off-by: Prajakta Gokhale <prajaktg@amazon.com>
Before the fix:
```bash
Running main() from /home/ANT.AMAZON.COM/prajaktg/ros2_ws/install-asan/gtest_vendor/src/gtest_vendor/src/gtest_main.cc
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from TestMessageSerialization
[ RUN      ] TestMessageSerialization.de_serialize_c
serialized data length: 52
serialized message c
00 01 00 00 01 ff 6b be 00 00 80 3f 00 00 00 00 00 00 00 40 03 04 05 00 06 00 be be 07 00 00 00 08 00 00 00 09 00 00 00 00 00 00 00 0a 00 00 00 00 00 00 00 
[       OK ] TestMessageSerialization.de_serialize_c (0 ms)
[ RUN      ] …
```

Fix memory leaks in test_communication tests

---

test_cli/CMakeLists.txt

Skip this test which fails very frequently for a long time on all platforms since there is no benefit to mark all all builds unstable because of it. Closes ros2/build_cop#166.
The issue ros2/system_tests#365 will track this problem with the goal to reenable the test when it is deterministic.

disable long term flaky test test_params_yaml

---

test_cli/CMakeLists.txt

Unveiled by https://github.com/ros2/ros2/issues/722

[test_cli] don't fail the build if the test is missing

---

test_rclcpp/test/test_multithreaded.cpp

Resolves build warnings due to `-Wsign-compare` with GCC 9.

Fix some comparisons with a sign mismatch

---

test_cli/package.xml

It never uses it, so we don't need it.
@sloretz It looks like you added this initially, but as far as I can tell this is never used in test_cli.  But let me know if I missed something.

Remove the test_cli dependency on launch.

---

test_communication/CMakeLists.txt

Fix regression from #322.
Before: https://ci.ros2.org/job/ci_windows/7438/testReport/(root)/test_communication/
After: https://ci.ros2.org/job/ci_windows/7439/testReport/(root)/test_communication/

fix condition to not skip FastRTPS to FastRTPS pub/sub tests

---

test_rclcpp/test/test_multithreaded.cpp

This is a backport of #373 for Dashing.
---
Resolves build warnings due to `-Wsign-compare` with GCC 9.

[Backport] Fix some comparisons with a sign mismatch

---

test_security/CMakeLists.txt

Since `DynamicArrayNested` doesn't exist anymore, this currently tests only against `Empty` messages
Signed-off-by: Mikael Arguedas <mikael.arguedas@gmail.com>

[test_security] use new message name

---

test_communication/CMakeLists.txt

These tests fail consistently due to an assertion in Fast-RTPS which was recently introduced.
Tracked by ros2/build_cop#230
Regressed by eProsima/Fast-RTPS#646
Reported upstream as eProsima/Fast-RTPS#671
Before: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=7979)](https://ci.ros2.org/job/ci_linux/7979/)
After: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=7980)](https://ci.ros2.org/job/ci_linux/7980/)

Skip rclcpp__rclpy__rmw_connext_cpp__rmw_fastrtps_cpp tests

---

test_communication/CMakeLists.txt

This reverts #382.
The issue was resolved by eProsima.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8023)](http://ci.ros2.org/job/ci_linux/8023/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4034)](http://ci.ros2.org/job/ci_linux-aarch64/4034/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=6534)](http://ci.ros2.org/job/ci_osx/6534/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=7877)](http://ci.ros2.org/job/ci_windows/7877/)

Revert "Skip rclcpp__rclpy__rmw_connext_cpp__rmw_fastrtps_cpp tests (#382)

---

test_cli/test/test_params_yaml.py
test_cli_remapping/test/test_cli_remapping.py

Precisely what the title says.
Connected to https://github.com/ros2/rcl/pull/491.

Use of -r/--remap flags where appropriate.

---

test_cli/test/test_params_yaml.py

This pull requests adapts `test_cli` to the changes introduced by https://github.com/ros2/rcl/pull/495.

Promote special CLI rules to flags.

---

test_rclcpp/test/test_intra_process.cpp

According to [here](https://github.com/ros2/rclcpp/blob/master/rclcpp/include/rclcpp/intra_process_manager.hpp#L72), intra_process still needs local pub and sub to send special msg info.
Therefore, I think we shouldn't set ignore_local_publications to true.
Signed-off-by: evshary <evshary@gmail.com>

Don't set ignore_local_publications = true.

---

test_quality_of_service/include/test_quality_of_service/qos_test_publisher.hpp
test_quality_of_service/include/test_quality_of_service/qos_test_subscriber.hpp

As per Clang:
```
--- stderr: test_quality_of_service                                                                                     
In file included from /Users/dan/Documents/ros2_ws/src/system_tests/test_quality_of_service/test/test_liveliness.cpp:31:
/Users/dan/Documents/ros2_ws/src/system_tests/test_quality_of_service/include/test_quality_of_service/qos_test_publisher.hpp:38:3: error: explicitly defaulted default constructor is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
QosTestPublisher() = default;
^
/Users/dan/Documents/ros2_ws/src/system_tests/test_quality_of_service/include/test_quality_of_service/qos_test_publisher.hpp:28:26: note: default constructor of 'QosTestPublisher' is implicitly deleted because base class 'QosTestNode' has no default constructor
class …
```

Remove broken constructors

---

test_rclcpp/CMakeLists.txt

Hopefully it'll solve test failures on Windows like https://ci.ros2.org/view/nightly/job/nightly_win_rel/1363/ (which doesn't show on https://ci.ros2.org/view/nightly/job/nightly_win_rel/1364/ so it's clearly a flake).
CI up to `test_rclcpp`:
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=8532)](http://ci.ros2.org/job/ci_windows/8532)

Bump test timeouts in test_rclcpp.

---

test_rclcpp/test/test_executor.cpp

Previously would constantly trigger based on a 0ms delay timer;
now only evaluates a single timer once per spin_some call. Test
now adds multiple timers with a short delay to simulate performing
work.
Relies on behavior change from ros2/rclcpp#844, addressing
ros2/rclcpp#471
Distribution Statement A; OPSEC #2893
Signed-off-by: Roger Strain <rstrain@swri.org>

Adjusted spin_some test due to new behavior

---

test_communication/test/test_messages_c.cpp

1. Use a macro to extract repeated logic
2. Check the sequence length so we get a test error message instead of segfaulting.
Signed-off-by: Dan Rose <dan@digilabs.io>

Clean up bounded sequences check

---

test_rclcpp/test/test_executable_output.py.in

In order to prevent tests breaking when the default logging format
changes, let's set an explicit log format for these test executables.
The tests are currently breaking because https://github.com/ros2/rcutils/pull/190 changed the default log format.

Set log format for test executables.

---

test_rclcpp/test/node_name_list.cpp

Related to ros2/rmw_connext#362 and ros2/ros2#489.
PR modifies existing node_name_list test that it would fail on getting an empty node name.
Connects to ros2/ros2#489

Modifying test for failing on getting an empty node name

---

test_cli_remapping/test/test_cli_remapping.py
test_communication/test/test_action_client_server.py.in
test_communication/test/test_publisher_subscriber.py.in
test_communication/test/test_requester_replier.py.in
test_rclcpp/test/test_executable_output.py.in
test_rclcpp/test/test_n_nodes.py.in
test_rclcpp/test/test_two_executables.py.in
test_security/test/test_secure_publisher_subscriber.py.in

The ready_fn will be deprecated in the future in favor of the ReadyToTest() action in launch_testing. See ros2/launch#346 (comment) for background information
**Note** I had some trouble getting these tests to build and run locally, so I'll pay extra-close attention to the CI jobs on this one
Signed-off-by: Pete Baughman <pete.baughman@apex.ai>

Replace ready_fn with ReadyToTest action

---

test_communication/test/test_action_client.cpp
test_communication/test/test_messages_c.cpp
test_communication/test/test_publisher_subscriber.cpp
test_communication/test/test_requester.cpp
test_quality_of_service/test/qos_test_publisher.cpp
test_quality_of_service/test/qos_test_subscriber.cpp
test_rclcpp/include/test_rclcpp/utils.hpp
test_rclcpp/test/parameter_fixtures.hpp
test_rclcpp/test/test_client_scope_client.cpp
test_rclcpp/test/test_intra_process.cpp
test_rclcpp/test/test_local_parameters.cpp
test_rclcpp/test/test_multithreaded.cpp
test_rclcpp/test/test_remote_parameters.cpp
test_rclcpp/test/test_spin.cpp
test_rclcpp/test/test_subscription.cpp

Style update to match the ROS 2 development guide and pass with the updated linter configuration from ament/ament_lint#210.

code style only: wrap after open parenthesis if not in one line

---

test_rclcpp/CMakeLists.txt

I'm not sure why this is not showing up yet on ci.ros2.org, but cppcheck fails to find some macros in test_rclcpp. This sets the appropriate ament_cmake variable to find their definitions.
Example failure:
http://build.ros2.org/view/Fci/job/Fci__nightly-debug_ubuntu_focal_amd64/lastCompletedBuild/testReport/
https://ci.ros2.org/view/nightly/job/nightly_windows-container_release/4/testReport/(root)/projectroot/cppcheck_2/
Builds with this PR
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9439)](http://ci.ros2.org/job/ci_linux/9439/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=5127)](http://ci.ros2.org/job/ci_linux-aarch64/5127/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7 …

Setting AMENT_CMAKE_CPPCHECK_ADDITIONAL_INCLUDE_DIRS with rclcpp

---

test_communication/CMakeLists.txt

To support more efficient CI builds as defined in ros2/ros_buildfarm_config#78.

add options to selectively ignore single/multi RMW tests

---

test_rclcpp/CMakeLists.txt
test_security/CMakeLists.txt
test_security/package.xml
test_security/test/test_invalid_secure_node_creation_c.cpp
test_security/test/test_secure_publisher.cpp
test_security/test/test_secure_subscriber.cpp

Updates:
- test_security https://github.com/ros2/rcl/pull/515.
- Disable failing cross-vendor tests, due to Fast-RTPS using one Participant per context.

Update test_security and test_rclcpp after one Participant per Context change

---

test_rclcpp/test/test_local_parameters.cpp

The type of the exception was changed in https://github.com/ros2/rclcpp/pull/1027

Update the expected exception thrown when getting an invalid parameter type

---

test_security/CMakeLists.txt

See https://github.com/ros2/rcl/pull/607.
Both should be merged together.

Use keystore root as security root directory, and not contexts folder

---

test_security/CMakeLists.txt

https://github.com/eProsima/Fast-RTPS/issues/1087 is the
issue that needs to be resolved.

Disable Fast-RTPS security tests until they work with OpenSSL 1.1.1{d,e,f}

---

test_security/CMakeLists.txt
test_security/test/test_invalid_secure_node_creation_c.cpp
test_security/test/test_secure_publisher.cpp
test_security/test/test_secure_subscriber.cpp

Signed-off-by: Mikael Arguedas <mikael.arguedas@gmail.com>

security-context -> enclave

---

test_communication/CMakeLists.txt

Only testing macOS since the patch just removes some tests (independent of the platform):
* Before [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8235)](https://ci.ros2.org/job/ci_osx/8235/)
* After: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8238)](https://ci.ros2.org/job/ci_osx/8238/)

disabled Connext-CycloneDDS WString tests

---

test_rclcpp/test/test_avoid_ros_namespace_conventions_qos.cpp
test_rclcpp/test/test_intra_process.cpp
test_rclcpp/test/test_multithreaded.cpp
test_rclcpp/test/test_publisher.cpp
test_rclcpp/test/test_subscription.cpp

Follow up of https://github.com/ros2/rclcpp/pull/1047, which broke nightly.

updates since changes to message_info in rclcpp

---

test_communication/CMakeLists.txt

When invoking CMake with `--warn-uninitialized`.

fix CMake warning about using uninitialized variables

---

test_communication/test/test_action_client.cpp
test_rclcpp/test/test_client_scope_client.cpp
test_rclcpp/test/test_client_scope_consistency_client.cpp
test_rclcpp/test/test_multithreaded.cpp
test_rclcpp/test/test_services_client.cpp
test_rclcpp/test/test_spin.cpp
test_rclcpp/test/test_subscription.cpp
test_rclcpp/test/test_waitable.cpp

avoid new deprecations

---

test_rclcpp/test/test_two_executables.py.in

This makes it easier to determine which tests are failing as we can see the gtest output.

Send output of test_rclcpp tests to screen

---

test_rclcpp/CMakeLists.txt

Currently `test_nodes_name` is enabled for fastrtps/fastrtps and  cyclonedds/connext. Cyclonedds uses one participant per context (ros2/rmw_cyclonedds#145) while Connext uses 1 participant per node (ros2/rmw_connext#381), so cyclone/connext is not expected to work and is currently failing in the nightlies.
* https://ci.ros2.org/job/nightly_linux_release/1527/testReport/(root)/projectroot/test_node_name__rmw_connext_cpp__rmw_cyclonedds_cpp/
* https://ci.ros2.org/job/nightly_linux_release/1527/testReport/(root)/projectroot/test_node_name__rmw_cyclonedds_cpp__rmw_connext_cpp/
This PR changes to what should work. FastRTPS uses 1 participant per context (https://github.com/ros2/rmw_fastrtps#312), so it should work with itself and Cyclonedds. Connext should only work with itself.
However, it …

Change which node name cross-vendor tests are enabled.

---

test_security/CMakeLists.txt

Ubuntu Focal, Homebrew and chocolatey now provide OpenSSL 1.1.1
RTI Connext 5.3.1 supports only 1.0.2 so we need to modify the library path and the path for connext's version of openssl be used when running tests with connext. Use system OpenSSL for other rmw implementations
related to https://github.com/ros2/ci/pull/421

Make Connext use Connext's openssl on all platforms

---

test_rclcpp/test/test_executor.cpp

Fixes https://ci.ros2.org/view/nightly/job/nightly_win_rel/1537/testReport/junit/test_rclcpp/test_executor__rmw_cyclonedds_cpp/spin_some_max_duration/.
Considering that the Windows scheduler time slice is [20ms](https://docs.microsoft.com/en-us/windows/win32/procthread/multitasking), the test is being too optimistic (same applies for macOS and Linux, though it was only failing on Windows).
I increased all durations, to ensure that the OS time slice doesn't represent a big fraction of it.

Make `test_executor.spin_some_max_duration` more reliable

---

test_rclcpp/CMakeLists.txt

Tracked at: https://github.com/ros2/rmw_cyclonedds/issues/183
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10744)](http://ci.ros2.org/job/ci_linux/10744/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6140)](http://ci.ros2.org/job/ci_linux-aarch64/6140/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8746)](http://ci.ros2.org/job/ci_osx/8746/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=10630)](http://ci.ros2.org/job/ci_windows/10630/)
Leveraging ability added here: ament/ament_cmake#240

disable flakey test

---

test_security/CMakeLists.txt

Reverts ros2/system_tests#413. To be tested and merged once Fast-RTPS has support for the necessary OpenSSL versions (https://github.com/eProsima/Fast-RTPS/issues/1087)

Re-enable Fast-RTPS security tests

---

test_security/CMakeLists.txt

Connext needs a different version of OpenSSL (1.0.2n) than the system
version.
Disabling these tests until we can figure out how to run them on CI. For more context see 
https://github.com/ros2/ci/pull/421/ and https://github.com/ros2/ci/pull/454
CI with changes in https://github.com/ros2/ci/pull/454: 
* Windows: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=10806)](https://ci.ros2.org/job/ci_windows/10806/)
* Windows Debug: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=10808)](https://ci.ros2.org/job/ci_windows/10808/)

Disable Connext security tests on Windows

---

test_security/CMakeLists.txt

Fixes https://github.com/ros2/system_tests/issues/432
This package artificially creates an invalid certificate for testing purposes. If compiling twice in a row, the invalid certificate is used to sign material and fails. This PR deletes the existing invalid certificate (and all the material related to this enclave), this ensures the regeneration of all material related to that enclave on rebuild.
Signed-off-by: Mikael Arguedas <mikael.arguedas@gmail.com>

remove invalid cert folder to force regeneration of certificates

---

test_rclcpp/package.xml

It is not used in test_rclcpp anywhere.

Remove ament_pytest dependency from test_rclcpp.

---

test_rclcpp/test/test_timeout_subscriber.cpp

When the test fails this actually show the nanoseconds of each duration rather than an `8-byte object`.
Allows to triage this long time failing test: https://ci.ros2.org/view/nightly/job/nightly_win_rel/1598/testReport/(root)/projectroot/gtest_timeout_subscriber__rmw_connext_cpp/
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11338)](http://ci.ros2.org/job/ci_linux/11338/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6575)](http://ci.ros2.org/job/ci_linux-aarch64/6575/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=9301)](http://ci.ros2.org/job/ci_osx/9301/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=11235)](http://ci.ros2.org/job/ci_w …

show numbers of nanseconds in EXPECT with durations

---

test_rclcpp/test/test_timeout_subscriber.cpp

This pull request: 
* Uses a nonzero lower bound for timeout checks if applicable.
* Relaxes time tolerance.
CI up to `test_rclcpp`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11361)](http://ci.ros2.org/job/ci_linux/11361/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6590)](http://ci.ros2.org/job/ci_linux-aarch64/6590/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=9315)](http://ci.ros2.org/job/ci_osx/9315/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=11247)](http://ci.ros2.org/job/ci_windows/11247/)

Fix rclcpp timeout subscriber test.

---

test_security/CMakeLists.txt

@SidFaber FYI this branch can be used for testing https://github.com/ros2/rmw_cyclonedds/pull/123.
As of https://github.com/ros2/rmw_cyclonedds/pull/123/commits/bca0852f502261484da318330f02a400473240b3 there are still some cases failing.
```
8 - test_secure_publisher_subscriber__Empty__rmw_cyclonedds_cpp__secure_comm_1 (Timeout)
9 - test_secure_publisher_subscriber__Empty__rmw_cyclonedds_cpp__secure_comm_2 (Timeout)
19 - test_secure_publisher_subscriber__UnboundedSequences__rmw_cyclonedds_cpp__secure_comm_1 (Timeout)
20 - test_secure_publisher_subscriber__UnboundedSequences__rmw_cyclonedds_cpp__secure_comm_2 (Timeout)
```

Run test_security on CycloneDDS as well

---

test_security/test/test_invalid_secure_node_creation_c.cpp

This PR updates `INSTANTIATE_TEST_CASE_P` to `-INSTANTIATE_TEST_SUITE_P`.

Update deprecated gtest macros

---

test_rclcpp/test/test_waitable.cpp

Fix tests after applying https://github.com/ros2/rclcpp/pull/1241 to fix https://github.com/ros2/rclcpp/issues/1212.

Modify to match Waitable interface adding take_data

---

test_rclcpp/CMakeLists.txt

The `test_rclcpp` cppcheck test timed out after 300 seconds in the latest Windows release nightly. Previous jobs took 273, 220, and 217 seconds. This increases it to 400.
There doesn't seem to be plumbing for setting a timeout with ament_cppcheck, so this sets the timeout on the test target directly.
https://ci.ros2.org/view/nightly/job/nightly_win_rel/1761

Set cppcheck timeout to 400 seconds

---

test_communication/test/test_action_client.cpp
test_communication/test/test_action_server.cpp
test_communication/test/test_publisher_subscriber.cpp

Several test configurations have been hanging, and I believe that's resolved by adding a corresponding shutdown to rclcpp::init.
Example failures:
https://ci.ros2.org/view/nightly/job/nightly_win_rel/1767/testReport/test_communication/
Testing `--packages-select test_communication`
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13193)](http://ci.ros2.org/job/ci_linux/13193/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8124)](http://ci.ros2.org/job/ci_linux-aarch64/8124/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10909)](http://ci.ros2.org/job/ci_osx/10909/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=13207)](http://ci.ros2.org/job/ …

Add corresponding rclcpp::shutdown to tests in test_communication

---

test_rclcpp/test/test_avoid_ros_namespace_conventions_qos.cpp
test_rclcpp/test/test_client_scope_client.cpp
test_rclcpp/test/test_client_scope_consistency_client.cpp
test_rclcpp/test/test_client_wait_for_service_shutdown.cpp
test_rclcpp/test/test_executor.cpp
test_rclcpp/test/test_intra_process.cpp
test_rclcpp/test/test_local_parameters.cpp
test_rclcpp/test/test_multiple_service_calls.cpp
test_rclcpp/test/test_multithreaded.cpp
test_rclcpp/test/test_publisher.cpp
test_rclcpp/test/test_remote_parameters.cpp
test_rclcpp/test/test_repeated_publisher_subscriber.cpp
test_rclcpp/test/test_services_client.cpp
test_rclcpp/test/test_services_in_constructor.cpp
test_rclcpp/test/test_spin.cpp
test_rclcpp/test/test_subscription.cpp
test_rclcpp/test/test_timeout_subscriber.cpp
test_rclcpp/test/test_timer.cpp
test_rclcpp/test/test_waitable.cpp

We're seeing many hangs on windows CI jobs in these tests, and I think the issue can be resolved by ensuring that `rclcpp::shutdown` gets called for each invocation of `rclcpp::init`. In the process of addressing this, I noticed that the test_remote_parameters wasn't setting up the test cases correctly for each rmw_implementation.
There may be some uncrustify issues to cleanup.
Testing `--packages-select test_rclcpp`
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13192)](http://ci.ros2.org/job/ci_linux/13192/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8123)](http://ci.ros2.org/job/ci_linux-aarch64/8123/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10908)](http://ci.ros2. …

Call rclcpp::init and rclcpp::shutdown in each test for test_rclcpp

---

test_rclcpp/test/parameter_fixtures.hpp
test_rclcpp/test/test_local_parameters.cpp

address https://github.com/ros2/rclcpp/issues/360, depends on https://github.com/ros2/rclcpp/pull/1493
Signed-off-by: Tomoya.Fujita <Tomoya.Fujita@sony.com>

update parameter client test with timeout.

---

test_communication/CMakeLists.txt
test_communication/package.xml
test_communication/test/test_action_client_server.py.in
test_communication/test/test_publisher_subscriber.py.in
test_communication/test/test_requester_replier.py.in

While debugging some failures over in https://github.com/ros2/rmw/pull/293, we came across a situation that seemed to make no sense.  The change from Fast-RTPS -> CycloneDDS as the default was causing *Connext* builds to fail.  After poking at it for a while, we think that an earlier running instance of the ros2 daemon is causing some incompatibilities for tests later on.
This PR changes it so that the test_communication tests always kill off the ros2 daemon before running tests, similar to how the ros2cli tests work.
Before: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13366)](http://ci.ros2.org/job/ci_linux/13366/)
After: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13376)](http://ci.ros2.org/job/ci_linux/13376/)
Full CI with this …

Ensure that the ros2 daemon is stopped before running system tests

---

test_rclcpp/test/test_client_scope_consistency_server.cpp
test_rclcpp/test/test_client_scope_server.cpp

Fixes #458.
An exception can be thrown if an interrupt occurs between checking rclcpp::ok() and rclcpp::spin_some().
Related to https://github.com/ros2/rclcpp/issues/1066

Guard against TOCTTOU with rclcpp::ok and rclcpp:spin_some

---

test_quality_of_service/CMakeLists.txt
test_quality_of_service/include/test_quality_of_service/qos_utilities.hpp
test_quality_of_service/test/qos_utilities.cpp
test_quality_of_service/test/test_deadline.cpp
test_quality_of_service/test/test_lifespan.cpp
test_quality_of_service/test/test_liveliness.cpp

As a result of the investigation for https://github.com/ros2/rmw_fastrtps/issues/384, it was apparent that `test_quality_of_service` tests were actually not being run. This patch corrects the situation.

Run QoS tests.

---

test_rclcpp/test/parameter_fixtures.hpp
test_rclcpp/test/test_local_parameters.cpp

Will be needed after https://github.com/ros2/rclcpp/pull/1522 to avoid deprecation warnings.

Adapt tests to statically typed parameters

---

test_communication/CMakeLists.txt
test_quality_of_service/test/test_deadline.cpp
test_quality_of_service/test/test_lifespan.cpp
test_security/CMakeLists.txt

This PR replaces all references to `rmw_connext_cpp` (and `rmw_connext_dynamic_cpp`) with `rmw_connextdds`.
See [rticommunity/rmw_connextdds #9](https://github.com/rticommunity/rmw_connextdds/issues/9) for a list of related PRs, and an overview of all the changes required to replace [ros2/rmw_connext](https://github.com/ros2/rmw_connext) (`rmw_connext_cpp`) with [rticommunity/rmw_connextdds](https://github.com/rticommunity/rmw_connextdds) in the ROS2 source tree.

Add support for rmw_connextdds

---

test_rclcpp/test/parameter_fixtures.hpp
test_rclcpp/test/test_timeout_subscriber.cpp

Some of the tests were susceptible at the amount of parameters declared, and https://github.com/ros2/rclcpp/pull/1532 is adding new parameters. That was fixed in https://github.com/ros2/system_tests/commit/f44712759998ca7c257b110f0fd4deac28e87724.
https://github.com/ros2/system_tests/commit/11d32755043faf733ce4e0f6993d46b69ad9bcf0 is a hack to fix a flaky test, I don't have a better way to test that in mind.

Make test pass after rclcpp#1532

---

test_rclcpp/test/parameter_fixtures.hpp
test_rclcpp/test/test_remote_parameters.cpp

depends on https://github.com/ros2/rclcpp/pull/1514
Signed-off-by: Tomoya.Fujita <Tomoya.Fujita@sony.com>

get_parameters_service_ should return empty if allow_undeclared_ is false

---

test_rclcpp/CMakeLists.txt

This reverts commit 4bedf8dcf7f78b69dd1721a999c40f443e9f4896. I've been unable to reproduce the original issue locally.
Trying repeated CI up to `test_rclcpp`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14114)](http://ci.ros2.org/job/ci_linux/14114/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8922)](http://ci.ros2.org/job/ci_linux-aarch64/8922/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11803)](http://ci.ros2.org/job/ci_osx/11803/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14210)](http://ci.ros2.org/job/ci_windows/14210/)

Revert "disable flakey test" (#431)

---

test_cli_remapping/test/test_cli_remapping.py

This fixes a flaky test caused by topic/service names used in two tests having a roughly 1 in 10,000 chance of colliding. It fixes the issue by changing the remapped string so they cannot collide (ts = topic and service, t = topic, s = service).
I also changed the arguments to a call to `format` to use a keyword argument directly instead of `**locals()` to be more transparent about what is being passed.
Flaky test failed in:
https://ci.ros2.org/job/nightly_linux_repeated/2256
Fixes #469

Fix test_cli_remapping flaky test

---

test_security/test/test_invalid_secure_node_creation_c.cpp

https://github.com/ros2/rcutils/pull/340 deprecates `rcutils/get_env.h`. This PR doesn't need to wait until the `rcutils` PR is merged, though.

Update includes after rcutils/get_env.h deprecation

---

test_security/CMakeLists.txt
test_security/test/test_secure_subscriber.cpp

The main reason to do this is that we were sometimes running out
of memory on the buildfarm while building this code.  I suspect
that it is because of the templated attempt_subscriber() functions
that had to get expanded for quite a few different messages.
However, it turns out that we were only ever using 2 of those
messages in tests themselves.  Simplify this whole thing by
only creating templated functions for the messages we are
actually going to use.
Similarly, simplify the quite complicated CMake logic a bit to
only have a list of the messages that we are going to actually
use.  If we want to add more messages in the future, we can
always expand this list again.
@nuclearsandwich FYI, I believe that this will solve the …

Simplify the test_secure_subscriber code.

---

test_communication/package.xml
test_communication/test/test_action_client.cpp
test_communication/test/test_action_server.cpp
test_communication/test/test_publisher_subscriber.cpp
test_rclcpp/package.xml
test_rclcpp/test/test_client_wait_for_service_shutdown.cpp

See https://github.com/ros2/rclcpp/issues/1725
This has to be merged before the header can be removed from `rclcpp`.
Signed-off-by: Christophe Bedard <bedard.christophe@gmail.com>

Use rcpputils/scope_exit.hpp instead of rclcpp/scope_exit.hpp

---

test_communication/CMakeLists.txt
test_rclcpp/CMakeLists.txt

Part of ros2/rosidl#606 which deprecates `rosidl_target_interfaces()` in favor of `rosidl_get_typesupport_target()`

Use rosidl_get_typesupport_target()

---

test_communication/test/test_publisher.cpp
test_communication/test/test_publisher_subscriber.cpp
test_communication/test/test_subscriber.cpp

`test_communication` makes tests for every message type in `test_interface_files`. This PR adds code support in the tests for the new message.
Requires https://github.com/ros2/rcl_interfaces/pull/125 - together they should fix the nightlies

Add tests for BoundedPlainSequences

---

test_cli/package.xml
test_cli_remapping/package.xml
test_communication/package.xml
test_quality_of_service/package.xml
test_rclcpp/package.xml
test_security/package.xml

Signed-off-by: Aditya Pande <aditya050995@gmail.com>

Updated maintainers

---

test_rclcpp/test/test_services_server.cpp

Relates to https://github.com/ament/ament_lint/pull/324

Fix include order for cpplint

---

test_rclcpp/test/test_multithreaded.cpp

Should address #487, checking with CI before merging.
Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>

Disable multithread intra process test on Foxy

---

test_communication/CMakeLists.txt
test_communication/test/subscribe_array_types.cpp
test_communication/test/subscribe_array_types.hpp
test_communication/test/subscribe_basic_types.cpp
test_communication/test/subscribe_basic_types.hpp
test_communication/test/subscribe_helper.hpp
test_communication/test/subscribe_string_types.cpp
test_communication/test/subscribe_string_types.hpp
test_communication/test/test_publisher_subscriber.cpp
test_communication/test/test_subscriber.cpp

This should avoid an OOM error when compiling on the buildfarm.
In particular, the https://ci.ros2.org/view/nightly/job/nightly_linux_coverage/ jobs have been flaky for the last two nights, failing while building exactly this.  In my testing, this reduces the maximum amount of resident memory needed for any one compilation unit from 2.9G to 1.9G.
Regular CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=16507)](http://ci.ros2.org/job/ci_linux/16507/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11094)](http://ci.ros2.org/job/ci_linux-aarch64/11094/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=16878)](http …

Split test_subscriber into multiple compilation units.

---

test_quality_of_service/CMakeLists.txt
test_quality_of_service/package.xml
test_quality_of_service/test/test_best_available.cpp

Testing feature added in https://github.com/ros2/rmw/pull/320 for all supported rmw implementations.
Test creating a subscription and publisher with 'best available' policies and confirm the actual
QoS policies are what we expect (adapting to an existing endpoint).

Add tests for 'best available' QoS policies

---

test_quality_of_service/CMakeLists.txt

There really isn't a reason to hard-code it here, and this
makes it match the rest of packages in this repository (and
in all of ROS 2 more generally).

Remove Werror from test_quality_of_service.

---

test_quality_of_service/test/test_best_available.cpp
test_rclcpp/test/test_client_scope_consistency_client.cpp
test_rclcpp/test/test_multithreaded.cpp

Part of ros2/rclcpp#1964
This passes `rclcpp::QoS` to `create_client`.

Pass rclcpp::QoS to create_client

---

test_cli/CMakeLists.txt
test_cli_remapping/CMakeLists.txt
test_communication/CMakeLists.txt
test_quality_of_service/CMakeLists.txt
test_rclcpp/CMakeLists.txt

The main reason to do this is so that we can compile the tests with the clang static analyzer.  As of clang++-14 (what is in Ubuntu 22.04), the default still seems to be C++14, so we need to specify C++17 so that new things in the rclcpp headers work properly.
Further, due to reasons I don't fully understand, I needed to set CMAKE_CXX_STANDARD_REQUIRED in order for clang to really use that version.  So set this as well.

Update the system tests to C++17.

---

test_quality_of_service/include/test_quality_of_service/qos_utilities.hpp
test_quality_of_service/test/test_best_available.cpp

to fix https://github.com/ros2/rmw_cyclonedds/issues/440
refer to [ros2cli](https://github.com/ros2/ros2cli/blob/14e640c6060fcb191eee266c55bbf4bed6ac97db/ros2cli/ros2cli/helpers.py#L25) to implement a `wait_for`, and then wait to call the `get_subscriptions_info_by_topic` or `get_publishers_info_by_topic` by a timeout.
NOTE: keep the https://github.com/iuhilnehc-ynos/system_tests/blob/5b4ee6075a4a67ef7f8efbf27e0fcdf3adda6888/test_quality_of_service/test/test_best_available.cpp#L57-L68 and https://github.com/iuhilnehc-ynos/system_tests/blob/5b4ee6075a4a67ef7f8efbf27e0fcdf3adda6888/test_quality_of_service/test/test_best_available.cpp#L114-L125 because they do assert in the tests even if it's not the intention for the test name.

avoid flaky test

---

test_quality_of_service/CMakeLists.txt
test_quality_of_service/include/test_quality_of_service/qos_test_node.hpp
test_quality_of_service/include/test_quality_of_service/qos_test_publisher.hpp
test_quality_of_service/include/test_quality_of_service/qos_test_subscriber.hpp
test_quality_of_service/include/test_quality_of_service/qos_utilities.hpp
test_quality_of_service/include/test_quality_of_service/visibility_control.hpp
test_quality_of_service/package.xml

`test_quality_of_service` is explicitly linking against gtest, but it gets linked again as a result of the `ament_add_gtest` call.
This causes an ODR violation, but it didn't seem to cause any issues with tests.
Running the QOS tests with asan causes ODR violations though.

Fix ODR errors with gtest

---

test_rclcpp/test/test_multithreaded.cpp

This is based on discussions with @clalancette and @mjcarroll about this test failing some times on low-core machines, the theory being that the timers all are waiting on the subscriptions, but doing so by blocking and therefore using all the executor threads. This change mainly changes this by having the timers give up after publishing everything and then having a separate thread to monitor the test and cancel the executor when done.

refactor the multi_access_publisher test to avoid dead locks

---

test_quality_of_service/CMakeLists.txt
test_quality_of_service/include/test_quality_of_service/qos_utilities.hpp

Fixes #517 by re-adding `target_link_libraries(${PROJECT_NAME}_support ${GTEST_LIBRARIES})` to `test_quality_of_service/CMakeLists.txt:47`.
Tested with macOS Ventura 13.4 arm64 and Docker container [arm64v8/ubuntu:latest](https://hub.docker.com/r/arm64v8/ubuntu/)

Fix test QoS on macOS by re-adding target_link_libraries *_support GTEST_LIBRARIES

---

test_rclcpp/test/parameter_fixtures.hpp

Part of ros2/ros2#1159
Linked with https://github.com/ros2/rclcpp/pull/2224
Fixes expected parameters, now that `start_type_description_service` is added.

new builtin parameter: fix test expectations

---

test_rclcpp/test/parameter_fixtures.hpp

Backport #520 to Iron
Depends on  ros2/rcl#1082
Linked to ros2/rclcpp#2236

[Iron] Add a fix for the tests given the new type description parameter (backport #520)

---

test_security/CMakeLists.txt

The current implementation creates SROS artifacts during the configure phase. This is undesirable for a variety of reasons, such as:
* The ros2 binary is invoked during build, meaning that a regression in that tool will break the entire CI build instead of appearing as a test failure.
* Some of the environment is captured during the artifact generation and it may not be the same when the tests are invoked. Namely, changes to ROS_DOMAIN_ID between build and test will break.
The test fixtures work similarly to tests themselves, and are automatically run if any tests requiring them are enabled. If the fixture fails, the dependent tests are not attempted.

Use test fixtures to create SROS artifacts

---

test_security/CMakeLists.txt
test_security/test/sros_artifacts.cmake

All of these commands should be run together to set up the fixture for the tests. When running tests with repitition, we want to run through the entire artifact setup and not run each individual command multiple times.
Fixes #522
CI, using `--retest-until-fail 2`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19310)](http://ci.ros2.org/job/ci_linux/19310/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13841)](http://ci.ros2.org/job/ci_linux-aarch64/13841/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20030)](http://ci.ros2.org/job/ci_windows/20030/)

Extract sros_artifacts fixture into a CMake script

---

test_rclcpp/CMakeLists.txt

Switch to target_link_libraries, and also only find the cpp typesupport once.  This slightly speeds up the build as a side bonus.

Cleanup of the CMakeLists.txt for test_rclcpp.

---

test_communication/test/test_publisher.cpp
test_communication/test/test_publisher_subscriber.cpp
test_security/test/test_secure_publisher.cpp

This is a adjustement fix for the test regressions appeared in `test_communication` and `test_security` after applying new `rclcpp::Rate` API (https://github.com/ros2/rclcpp/pull/2123).
The new `rclcpp::Rate` API after the change implies that RCLCPP context should exist at the `rate.sleep()` call time. However, internal test publisher's logic does not destroy the `Rate` objects after RCLCPP was stopped, which causes a runtime exceptions. Moreover, there are some tests (named `**AfterShutdown`), that intentionally runs the subscriber and publisher nodes (with `rclcpp::Rate` working inside) after the context was stopped and checks that everything is just closed correctly. This in our case is also causing the same run-time exception.
Thus, without large test modification, it is seems to be …

Adjust for new rclcpp::Rate API

---

test_communication/CMakeLists.txt
test_communication/msg/Inner.msg
test_communication/msg/Outer.msg
test_communication/test/test_nested_types.cpp

This is an integration test to ensure that https://github.com/ros2/rmw_fastrtps/issues/715 doesn't happen again.

Add integration test for nested messages.

---

test_rclcpp/CMakeLists.txt

It fails only on Connext, and via debugging it seems like the problem is in Connext itself.

Mark gtest_subscription__rmw_connextdds xfail.

---

test_cli/CMakeLists.txt
test_cli_remapping/CMakeLists.txt
test_communication/CMakeLists.txt
test_quality_of_service/CMakeLists.txt
test_security/CMakeLists.txt

While we are in here, also remove some dead code relating to old RMWs that no longer exist.
A draft for now since I want to run CI to ensure that we are running all of the same tests.

Switch to target_link_libraries everywhere.

---

test_rclcpp/CMakeLists.txt
test_rclcpp/test/node_check_names.cpp
test_rclcpp/test/test_avoid_ros_namespace_conventions_qos.cpp
test_rclcpp/test/test_client_scope_client.cpp
test_rclcpp/test/test_client_scope_consistency_client.cpp
test_rclcpp/test/test_client_wait_for_service_shutdown.cpp
test_rclcpp/test/test_executor.cpp
test_rclcpp/test/test_intra_process.cpp
test_rclcpp/test/test_local_parameters.cpp
test_rclcpp/test/test_multiple_service_calls.cpp
test_rclcpp/test/test_multithreaded.cpp
test_rclcpp/test/test_publisher.cpp
test_rclcpp/test/test_remote_parameters.cpp
test_rclcpp/test/test_repeated_publisher_subscriber.cpp
test_rclcpp/test/test_services_client.cpp
test_rclcpp/test/test_services_in_constructor.cpp
test_rclcpp/test/test_services_server.cpp
test_rclcpp/test/test_sigint_handler.cpp
test_rclcpp/test/test_sigterm_handler.cpp
test_rclcpp/test/test_spin.cpp
test_rclcpp/test/test_subscription.cpp
test_rclcpp/test/test_timeout_subscriber.cpp
test_rclcpp/test/test_timer.cpp
test_rclcpp/test/test_waitable.cpp

Instead of recompiling the tests multiple times for each RMW, instead just compile it once and use the RMW_IMPLEMENTATION environment variable to control which RMW gets used.  On my machine, this sped up
compilation by about 2x, and should reduce the number of times our coverage jobs fail because they run out of memory.

Revamp test_rclcpp to compile far few files.

---

test_rclcpp/test/test_avoid_ros_namespace_conventions_qos.cpp
test_rclcpp/test/test_multithreaded.cpp
test_rclcpp/test/test_publisher.cpp
test_rclcpp/test/test_subscription.cpp

Newer uncrustify changes the indentation around lambdas. Avoid that here by making sure the lambdas are all on either one or two lines, which should make this work for both current and newer uncrustify.

Change up the formatting in the test_rclcpp tests.

---

test_rclcpp/test/node_name_list.cpp
test_rclcpp/test/node_with_name.cpp

We do a few things here:
1.  Minor style updates, just to make the code easier to read.
2.  Increase the timeout for finding the node from 10 seconds to 15 seconds.
3.  Change the call to the executor from spin_once to spin_some. This means that we'll give the executor more opportunity to do work, which may increase the chances of success.

Improve the node_name test.

---

test_rclcpp/CMakeLists.txt

After a relatively recent refactoring, the old way we were marking to skip the test no longer worked (because in the new system, there are no targets that are actually named gtest_subscription__rmw_connextdds).  Use another method to skip the test.

Actually skip the gtest_subscription test on Connext.

---

test_rclcpp/test/test_waitable.cpp

This API methods were deprecated on `jazzy` 
- `https://github.com/ros2/rclcpp/blob/jazzy/rclcpp/include/rclcpp/waitable.hpp#L139-L143` https://github.com/ros2/rclcpp/blob/jazzy/rclcpp/include/rclcpp/waitable.hpp#L112-L116
- `is_ready` https://github.com/ros2/rclcpp/blob/jazzy/rclcpp/include/rclcpp/waitable.hpp#L139-L143
- execute https://github.com/ros2/rclcpp/blob/jazzy/rclcpp/include/rclcpp/waitable.hpp#L223-L227
This PR uses the right methods

Update deprecated methods
